### ISSUE TITLE
Navigation - toggle

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#109]

**Comment by zufrieden** [comment]
toggle title :Focus is not good, check with a designer ;-)

![screenshot 2018-06-06 12 45 16](https://user-images.githubusercontent.com/451236/41033675-af4bff20-6987-11e8-9ab8-976101132784.png)

**Comment by knuch** [comment]
@zufrieden this issue is about the navigation, not the toggle component ^_^
