### ISSUE TITLE
Color palette limitation

### ISSUE THREAD

**Issue by guillaumeberry** [epfl-idevelop/elements#124]
Based on the [Color design review PR](https://github.com/epfl-idevelop/elements/pull/98), we should not make the **$blue** + **$orange** + **$green** available in:
- the Brand colors
- the Accessibility Table

Those 3 colors are ONLY used in the "alerts" component. 

Thanks!

**Comment by Yago** [comment]
done in a6e845cb9ddb60614923ba8ec3eaf9f640b0885d 😉
