### ISSUE TITLE
News page

### ISSUE THREAD

**Issue by guillaumeberry** [epfl-idevelop/elements#128]
- [ ] 👤 **Header** should be the **light version** (same as the [news detail page](https://github.com/epfl-idevelop/elements/issues/126))
- [ ] 👣 **Footer** should be the **light version**
- [ ] [Highlighted teaser](http://localhost:3000/#/organisms/news): content (title+category+button+teaser) should be either bottom or top or right aligned (see mockups [here](https://invis.io/N4FDSKWX8ZB#/279352922_News))
- [ ] **Remove load more button** (leave only pagination

--- LATER ---
- [ ] **Filters**: a proposal was made to display/trigger/hide the filters (see attached capture)

---

![filtres](https://user-images.githubusercontent.com/33514073/40787968-2b5d2708-64ef-11e8-9248-b20adc925ca6.png)

**Comment by zufrieden** [comment]
@guillaumeberry Need some UX discussion with me ;-)

**Comment by zufrieden** [comment]
Duplicate with https://github.com/epfl-idevelop/elements/issues/233
