### ISSUE TITLE
[4h] Re-organize styleguide structure

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#138]
- [x] Define structure ;-) @zufrieden
~- [ ] Allow 3 levels in toolbox @Yago~

**Comment by Yago** [comment]
What's the purpose of having 3 levels ?

**Comment by zufrieden** [comment]
We opened a discussion with every member of the project in order to define a better pages/components/structure for Elements.

Here is our proposal. Open to discussion of course, but we need a validation as soon as possible, as it impacts our deliverables (for the next 3 weeks ;-))

## Our process to define the structure
We identified different target audiences for Elements and what are their needs:

1. Mediacom **Owning Elements as the source of truth on how to respect brand identity online**
2. Webmasters **Seeking information on how to arrange component on their WordPress website**
3. VPSI **Seeking information on how to implement frontend code (CSS/JS) into their backend apps and WordPress themes and which HTML structure to respect**
4. Elements contributors **Seeking information on how to install and contribute to Elements**

## Structure proposition
Elements
├── Homepage → Guide user to Why Elements? Where to start? How to contribute?
├── Colors → Easy access guide of the project's colors
├── Documentation
│   ├── Design documentation → Design principles, Typography
│   ├── Contribute to Elements → How to install Elements, Pull request etc...
│   ├── Accessibility → Basics and links to more informations
│   └── Wordpress → Explain briefly wordpress architecture + Link to a wordpress shortcode demo website 
├── Atoms → Extra small components
├── Molecules → Medium sized components
├── Organisms → Large components
├── Content types → Document each content types (event, news,...) and it display modes (teaser, full,...)
└── Pages → Link to exemple pages with guided tour

**Comment by frizzymagma** [comment]
To us, this make total sense. We do validate this proposition. Thanks

**Comment by zufrieden** [comment]
Thank you :-)

**Comment by zufrieden** [comment]
@knuch @Yago thank you
