### ISSUE TITLE
Missing components in Elements

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#154]
Hello @zufrieden , 
I just wanted to point out that there were some components missing in the Elements Styleguide: 

- Event : il manque le "listing" des événements (le composant apparaît sur https://projects.invisionapp.com/share/ETEEFVHSQ#/screens/286230780 et est listé dans la matrice des composants)
- Contact : il manque les petits blocs de contact "light" (le composant apparaît sur https://projects.invisionapp.com/share/ETEEFVHSQ#/screens/295830528)

I'll check again the whole styleguide once I'll be back in a couple of weeks.

**Comment by zufrieden** [comment]
Thank you for your feedback.

**Comment by zufrieden** [comment]
Missing elements implemented ;-)

- [x] event listing with 1 highlight https://epfl-idevelop.github.io/elements/#/content-types/event/highlight-listing/full
- [x] contact listing https://epfl-idevelop.github.io/elements/#/pages/people-list
