### ISSUE TITLE
Breadcrumb DAG - Lot5

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#157]
- [ ] Add tags between HOME and the breadcrumb
- [x] Discuss with @guillaumeberry :-)

**Comment by pierre-georges** [comment]
Design updated @guillaumeberry @zufrieden.
https://invis.io/9DMZV08HJ6Z#/310515763_Breadcrumb_DAG

**Comment by zufrieden** [comment]
Thank you @pierre-georges 
Design-wise it's exactly what we needed.

-> Tags are only on the higher parent level so HOME > TAG | TAG | TAG | Parent > Child page > Current page

**Comment by zufrieden** [comment]
<img width="1253" alt="screenshot 2018-07-24 17 38 49" src="https://user-images.githubusercontent.com/451236/43149705-718e0aa0-8f68-11e8-9d47-4172970617db.png">


- [ ]  Pearing with a frontend ;-)
- [ ]  make sure mobile version of tags works (long sentence) Think of "Chemistry and Chemical Engineering Section SB-SCGC"

**Comment by Yago** [comment]
Done in 180304bde253e2169ebf0c8b86965751f8146779
