### ISSUE TITLE
Quote

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#159]
<img width="842" alt="screenshot 2018-07-23 21 41 09" src="https://user-images.githubusercontent.com/451236/43099041-27468f78-8ec1-11e8-958f-d4c756fc3576.png">
<img width="425" alt="screenshot 2018-07-23 21 41 14" src="https://user-images.githubusercontent.com/451236/43099043-27678340-8ec1-11e8-914a-4fcb09ff3a6f.png">

**Comment by Yago** [comment]
@zufrieden @guillaumeberry @pierre-georges Why is that so different of the normal blockquote element (see [Typography doc](https://epfl-idevelop.github.io/elements/#/doc/typography.html)) ? Can we harmonize both elements to have only variations on the font-size and the avatar ?

**Comment by guillaumeberry** [comment]
Yes we can @Yago !

**Comment by zufrieden** [comment]
@pierre-georges discuss this with @Yago ;-)

**Comment by zufrieden** [comment]
- [ ] When ready add it to about page
