### ISSUE TITLE
Accueil association

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#161]
## Examples 
[clic.epfl.ch](https://clic.epfl.ch/)

## Goal
- Explain what this association is about

### Context
Component : [Hero](https://epfl-idevelop.github.io/elements/#/components/hero)
The association title, cover image and introduction text about all the good stuff that are made here, the news and the passionate people who work here. It's always interesting to know in few lines what is all about.
### Current events
Component : [Event](https://epfl-idevelop.github.io/elements/#/content-types/event) (Slider wrapper)
There are many activities within EPFL, this section highlights those who go on in the association
### News
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news) (basic teaser)
The last 3 news shows what is happening in this association
### Team
Component : [Basic page](https://epfl-idevelop.github.io/elements/#/content-types/basic-page)
Some visitors may want to ask you questions or see who composes the laboratory's team. It is possible to link to the team page using the Teaser basic page component.
### Sponsorship
Component : [Sponsor](https://epfl-idevelop.github.io/elements/#/molecules/sponsor) 
It is possible that you have sponsors. You can list them thanks to the Media component (Sponsor).
### Contact
Component : [Contact](https://epfl-idevelop.github.io/elements/#/organisms/contact) (Banner)
Several people may want to contact the association: press, potential collaborators, people interested in your work or simply people who want to know where you are located. 
## Open questions
- Where goes the association logo ?

**Comment by nsz** [comment]
Ajouter un flux des réseaux sociaux

à coder

**Comment by nsz** [comment]
@guillaumeberry @zufrieden 
publié et ready to review : https://epfl-idevelop.github.io/elements/#/pages/association-homepage

**Comment by zufrieden** [comment]
Good for me 👍 

Just changed footer to footer light
@frizzymagma you'll be able to check on the next release
