### ISSUE TITLE
Accueil site événement

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#162]
## Examples 
[dronedays.epfl.ch](https://dronedays.epfl.ch/fr/index-fr-html/)

## Goal
- Explain what this event is about, where and when it happens.

### Context
Component : [Hero](https://epfl-idevelop.github.io/elements/#/organisms/hero)
The event title, cover image and introduction text about the event. It's always interesting to know in few lines what is all about.
### News
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news) (basic teaser)
The last 3 news shows if there is something new about the event.
### Useful information
Component : [basic page](https://epfl-idevelop.github.io/elements/#/content-types/teaser-basic-page)
Where, when, how, inscriptions, etc. It is useful to have a link on the homepage to these informations.
### Activities/Program
Component : [basic page](https://epfl-idevelop.github.io/elements/#/content-types/teaser-basic-page)
What happens during the event. It is useful to have a link on the homepage to these informations.
### Sponsorship/Partners
Component : [Sponsor](https://epfl-idevelop.github.io/elements/#/molecules/sponsor)  
It is possible that you have sponsors. You can list them thanks to the Sponsor component.
### Contact
Component : [Contact](https://epfl-idevelop.github.io/elements/#/organisms/contact) (Banner)
Several people may want to contact the event: press, potential collaborators, people interested in your work or simply people who want to know where you are located. 
### [Footer](https://epfl-idevelop.github.io/elements/#/organisms/footer)

**Comment by nsz** [comment]
à coder !

**Comment by nsz** [comment]
ready to review https://github.com/epfl-idevelop/elements/pull/216/commits/0077d19f2e6faba4e8bc85692d436f3093d9c6f2

**Comment by nsz** [comment]
@guillaumeberry  @zufrieden publié, ready to review : https://epfl-idevelop.github.io/elements/#/pages/event-homepage

**Comment by zufrieden** [comment]
good for me to go :-)
Add footer light

@frizzymagma you'll be able to check on the next release
