### ISSUE TITLE
Toutes les associations

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#165]
## Goal
- List associations

### Context
Component : [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Title, explication about what is an association in the EPFL
### Associations list
Component : [Association](https://epfl-idevelop.github.io/elements/#/content-types/association) 
Because there are a large number of laboratories, it is more judicious to display them as a list.
### Filters
Component : [Filters](https://epfl-idevelop.github.io/elements/#/molecules/filters) ?
It can be interesting to filter associations by category 
## Open questions
- Is a [pagination](https://epfl-idevelop.github.io/elements/#/molecules/pagination) necessary ?

**Comment by nsz** [comment]
catégories : 
Aide à la vie professionnelle
Animation
Développement
Etudiants EPFL 
Etudiants par pays 
Représentation de membres EPFL 
Science & Culture
Sport
Divers 

à coder !

**Comment by nsz** [comment]
https://github.com/epfl-idevelop/elements/pull/216/commits/e89cac8c1346d313dd56cb910b2a29ab35ff69d6

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, ready to review : https://epfl-idevelop.github.io/elements/#/pages/association-list

**Comment by zufrieden** [comment]
Good for me.

Need your validation @frizzymagma 
https://epfl-idevelop.github.io/elements/#/pages/association-list
