### ISSUE TITLE
Page qui liste toutes les filières

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#166]
## Goal
- List sections

### Context
Component : [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Title, explication about what is a section in the EPFL
### Section list
Component : [Teaser mission](https://epfl-idevelop.github.io/elements/#/content-types/section)*
## Open questions
- Should we be able to compare them? Like https://bachelor.epfl.ch/orientation ?
- Who will consult this page?
- Are filters needed? There isn't a large number of section

**Comment by nsz** [comment]
Pour commencer : simplement la liste
à coder !

**Comment by nsz** [comment]
ready to review : https://github.com/epfl-idevelop/elements/pull/216/commits/7472f9e24def0476d1686147bffa2ba73fd3abaa

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, à review : https://epfl-idevelop.github.io/elements/#/pages/programs

**Comment by zufrieden** [comment]
Good for me

@frizzymagma need your review here 
https://epfl-idevelop.github.io/elements/#/pages/programs
