### ISSUE TITLE
Accueil blog

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#168]
## Goal
- Publish articles on a theme

### News
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news)
- Highlighted
- Basic teaser
This page lists the different news, it is possible to put one forward with the teaser "highlighted".
### [Footer](https://epfl-idevelop.github.io/elements/#/organisms/footer)

**Comment by nsz** [comment]
à coder !

**Comment by nsz** [comment]
ready to review : https://github.com/epfl-idevelop/elements/pull/216/commits/0310652971fd4a3943c007924fb2bed29368479e

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, ready to review : https://epfl-idevelop.github.io/elements/#/pages/blog-homepage

**Comment by zufrieden** [comment]
Good for me
Just added footer light version
@frizzymagma you'll be able to check on the next release
