### ISSUE TITLE
Facultés --> page de "niveau 1"

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#169]
## Goal
- List the faculties
### Context
Component : [Introduction](https://epfl-idevelop.github.io/elements/#/organisms/introduction)
Title, explication about what is a faculty in the EPFL
### Faculties list
Component : [Faculty](https://epfl-idevelop.github.io/elements/#/content-types/faculty)

**Comment by nsz** [comment]
Faut-il ajouter les instituts ?
**à faire valider par Corinne**

**Comment by cfeuz** [comment]
ok

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, ready to review : https://epfl-idevelop.github.io/elements/#/pages/facultes

**Comment by zufrieden** [comment]
Good for me just updated sidenav with the list of faculties
@frizzymagma you'll be able to check on the next release
