### ISSUE TITLE
Campus --> page de "niveau 1"

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#176]
[Wireframe](https://invis.io/KJN0UK34D2C#/261731487_Campus)
## Goal
- Give all practical information to (future) students
- Redirect visitors for everything that concerns the campus life at EPFL (map, events, schedule, etc.)
### Context
Component : 
- [Hero](https://epfl-idevelop.github.io/elements/#/organisms/hero)
Title, image
- [Link](https://epfl-idevelop.github.io/elements/#/molecules/links-group) 
Useful links (help, tips, parking, etc.)
### Location
Component : 
- [Basic page](https://epfl-idevelop.github.io/elements/#/content-types/basic-page)
Link to the campus map
- [Basic page](https://epfl-idevelop.github.io/elements/#/content-types/basic-page)
Link to the virtual tour
- "Se rendre à l'EPFL" --> missing ?
### Event
Component : [Event](https://epfl-idevelop.github.io/elements/#/content-types/event) (Slider wrapper)
Next events
### News
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news) 
Latest news about the EPFL and link to all the news
### Live in Lausanne
Component :
- Text and link (know more about Lausanne)
- [Link](https://epfl-idevelop.github.io/elements/#/molecules/links-group)  
Settle in Lausanne
- [Link](https://epfl-idevelop.github.io/elements/#/molecules/links-group) 
Live in Lausanne 
### Associations / Building & services
Component :
- [Basic page](https://epfl-idevelop.github.io/elements/#/content-types/basic-page)
Link to the associations list
- [Link](https://epfl-idevelop.github.io/elements/#/molecules/links-group)  
Link to all the buildings (libraries, restaurants, etc.)
### [Footer](https://epfl-idevelop.github.io/elements/#/content-types/footer)

**Comment by nsz** [comment]
- chiffres clés : les chiffres viennent d'une base de données ? est-ce dynamique ?
- ajouter le contact du guichet des étudiants ?
**à valider par Adrian**

**Comment by cfeuz** [comment]
les chiffres clés viendront à terme d'une base dynamique mais il faut qu'on fasse avec un élément en dur pour l'instant

et oui contact guichet étudiant à ajouter

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, à reviewer : https://epfl-idevelop.github.io/elements/#/pages/campus

**Comment by zufrieden** [comment]
We just need #238 to be ready
