### ISSUE TITLE
Listing événements (memento)

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#177]
## Goal
- List all the events

### Calendar
Component : [Datepicker](https://epfl-idevelop.github.io/elements/#/molecules/datepicker) 
### Filters
Component : [Filters](https://epfl-idevelop.github.io/elements/#/molecules/filters) ?
It can be interesting to filter events by publics and categories
### Events list
Component : [Event](https://epfl-idevelop.github.io/elements/#/content-types/event)
## Open questions
- Is a [pagination](https://epfl-idevelop.github.io/elements/#/molecules/pagination) necessary ?

**Comment by nsz** [comment]
@frizzymagma

**Comment by frizzymagma** [comment]
@nsz A nouveau, il s'agit d'un outil, et non pas de WordPress. 

Header --> header light outil (avec nom de l'outil à côté du logo EPFL)

Pas de breadcrumb

Titre --> titre du canal d'événements sur lequel on se trouve

Calendrier

Filtres

Listing d'événements --> classement par catégorie d'événements ? toujours utile / pertinent ? 

Footer --> footer light

Pagination --> pas nécessaire

**Comment by zufrieden** [comment]
@frizzymagma ready to review on your side : https://epfl-idevelop.github.io/elements/#/pages/event-list

**Comment by frizzymagma** [comment]
C'est bon de notre côté. Nous avons envoyé les infos aux dev qui vont adapter l'outil memento.epfl.ch 

[New layout memento.epfl.ch-1.pdf](https://github.com/epfl-idevelop/elements/files/2313256/New.layout.memento.epfl.ch-1.pdf)
