### ISSUE TITLE
Publications - Add image

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#178]
Publications - Proposition d'une variation du composant avec l'affichage d'une image (facultative) voir l'exemple sur infoscience

https://infoscience.epfl.ch/search?ln=en&p=cloud&f=&c=Infoscience%2FArticle&c=Infoscience%2FReview&c=Infoscience%2FThesis&c=Infoscience%2FWorking+papers&c=Infoscience%2FProceedings&c=Infoscience%2FPresentation&c=Infoscience%2FPatent&c=Infoscience%2FStudent&c=Media&c=Work+done+outside+EPFL&c=Infoscience%2FConference&c=Infoscience%2FReport&c=Infoscience%2FBook&c=Infoscience%2FChapter&c=Infoscience%2FPoster&c=Infoscience%2FStandard&c=Infoscience%2FLectures&c=Infoscience%2FDataset&c=Infoscience%2FPhysical+objects&c=Other+doctypes&sf=&so=d&rg=10

<img width="908" alt="screenshot 2018-07-24 17 27 51" src="https://user-images.githubusercontent.com/451236/43149087-f2df97a6-8f66-11e8-8e08-b08b2a2cd843.png">

Actuellement 

<img width="841" alt="screenshot 2018-07-24 17 29 04" src="https://user-images.githubusercontent.com/451236/43149169-197c5eee-8f67-11e8-866b-e360c2f19174.png">

**Comment by pierre-georges** [comment]
Design updated.
https://invis.io/9DMZV08HJ6Z#/279353740_Publication
