### ISSUE TITLE
Listing Actualités (actus.epfl.ch)

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#181]
## Goal
- List all the news

### Filters
Component : [Filters](https://epfl-idevelop.github.io/elements/#/molecules/filters) ?
It can be interesting to filter events by publics and categories
### News list
Component : [News](https://epfl-idevelop.github.io/elements/#/content-types/news)
## Open questions
- Is a [pagination](https://epfl-idevelop.github.io/elements/#/molecules/pagination) necessary ?

**Comment by nsz** [comment]
à coder !

**Comment by nsz** [comment]
https://github.com/epfl-idevelop/elements/pull/216/commits/e3e1175b50cf72dba01f64d5e972085d9a0d73d3

**Comment by frizzymagma** [comment]
@nsz Attention, pour actu.epfl.ch, memento.epfl.ch et people.epfl.ch, il ne s'agit pas du tout de WordPress ! 

Le header à mettre n'est pas le "header complet", mais le "header light", avec le nom de l'outil à côté du logo, comme il avait été défini avec @guillaumeberry 

Il n'y a pas de breadcrumb, et il s'agit du footer light.

**Comment by frizzymagma** [comment]
Selon la proposition qui a été validée, il faut que sur la page d'accueil actu.epfl.ch il faut que nous puissions **prioriser** les actualités : à savoir, une grande actualité principale, deux actualités (ou 3 ? je ne me souviens plus ce que @guillaumeberry avait proposé) secondaires, et un listing d'actualités. 

Merci.

**Comment by frizzymagma** [comment]
Pour les 7 canaux d'actualités principaux, il faudrait avoir 2 actualités mises en avant, puis le listing d'actualités avec le reste des actus du canal en question.

**Comment by frizzymagma** [comment]
Probablement besoin d'une pagination, car sinon, il y a énormément d'actualités à charger.

**Comment by nsz** [comment]
@frizzymagma 
- Ok pour "pas un wordpress" (header light, pas de breadcrumb, pas de sidebar, footer light).
- Ok pour 1 actu principale avec 2 en-dessous puis un listing
- Ok pour la pagination
- Pour les filtres, nous avons pour l'instant utilisé le composant existant
- Pour les canaux, je laisse @guillaumeberry te répondre.

**Comment by guillaumeberry** [comment]
@frizzymagma @nsz 

Alors pour les canaux, effectivement il y a dans ma proposition un menu déroulant qui permet d'afficher les "sous-pages" par canal. On arrive sans doute à une bonne solution en insérant un composant "[drop-down](https://epfl-idevelop.github.io/elements/#/atoms/dropdown)" dans le header-light.

Ma maquette faisait référence au style qu'on avait maquetté pour la navigation principale… Il y a un bon moment. Donc un développement qui n'a pas eu lieu. 

Est-ce que la solution du drop-down convient ? 🤓

**Comment by frizzymagma** [comment]
@guillaumeberry Oui, on te fais confiance. 😉

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, à reviewer : https://epfl-idevelop.github.io/elements/#/pages/news-homepage

**Comment by zufrieden** [comment]
Good for me. Just added space between listing and pagination
@frizzymagma you'll be able to check on the next release
