### ISSUE TITLE
People - no image

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#182]
### What I Have 
https://epfl-idevelop.github.io/elements/#/pages/people-page
<img width="520" alt="capture d ecran 2018-07-26 a 11 47 43" src="https://user-images.githubusercontent.com/1941982/43255286-bcf96022-90c9-11e8-80d7-3f54f0853e3c.png">

### What I Want
Corinne demande si à la place du rond avec 190x190 on peut mettre par défaut une image d'une silhouette ?

**Comment by guillaumeberry** [comment]
Proposition d'image de profile par défaut, neutre de genre.
![avatar-test](https://user-images.githubusercontent.com/33514073/43882885-996b89a8-9bb1-11e8-87c6-38469a5d850b.png)

Si ça convient, voici le fichier SVG :
- couleur de background : $gray-100 #E6E6E6
- couleur du pictogramme : $black #212121

[profile-picture_default.svg.zip](https://github.com/epfl-idevelop/elements/files/2273083/profile-picture_default.svg.zip)
