### ISSUE TITLE
[In WP] Positionnement du label sur les checkbox et les radios dans les formulaires

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#183]
- Composants
	- Organisms -> Form
	- Molecules -> Form group
	- Atoms -> Checkbox
	- Atoms -> Radio
        - Molecules -> Filters

- Url
	- https://migration-wp.epfl.ch/styleguide-qa/organisms/form/
	- https://migration-wp.epfl.ch/styleguide-qa/molecules/filters/

- Version
	- epfl-theme 0872446, Jul 17, 2018 
	- elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
