### ISSUE TITLE
[In WP] Alignement vertical des textes dans les boites Collapse

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#184]
- Composants
	- atoms -> collapse
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/atoms/collapse/
- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
