### ISSUE TITLE
[In WP] La navigation par langue ne s'affiche pas correctement

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#186]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/atoms/nav-lang/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
