### ISSUE TITLE
[In WP] Nav toggle n'a pas son icon

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#187]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/atoms/nav-toggle/
- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
