### ISSUE TITLE
[In WP] L'affichage des pictures s'étend et étire le format original

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#188]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/atoms/picture/
- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
