### ISSUE TITLE
[In WP] L'icon Popover est en difficulté

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#189]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/atoms/popover/
	- https://migration-wp.epfl.ch/styleguide-qa/molecules/cover/
- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
