### ISSUE TITLE
[In WP] L'avatar n'est pas aligné avec son nom

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#191]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/molecules/avatar-teaser/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
