### ISSUE TITLE
[In WP] Les flèches du Collapse group sont alignées trop bas

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#194]
- Urls
    - https://migration-wp.epfl.ch/styleguide-qa/molecules/collapse-group/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
