### ISSUE TITLE
[In WP] Les cases à cocher du second groupe des filters fonctionnent de manière biscornue 

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#196]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/molecules/filters/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
