### ISSUE TITLE
[In WP] Les logos des réseaux sociaux sont baveux dans social feed

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#198]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/molecules/social-feed/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
