### ISSUE TITLE
[In WP] Les boutons de controle sont agencé approximiativement dans le card slider

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#199]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/organisms/card-slider/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment, voir commentaire: https://github.com/epfl-idevelop/elements/issues/207
