### ISSUE TITLE
[In WP] Le dark footer n'est pas très dark

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#201]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/organisms/footer/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
Je ne semble pas pouvoir reproduire votre souci. Est-ce que vous auriez un screenshot à disposition? Voici ce que je vois

<img width="1315" alt="capture d ecran 2018-08-07 a 14 40 08" src="https://user-images.githubusercontent.com/4548432/43776340-ce508f5a-9a4f-11e8-86d7-d1b12690594c.png">
