### ISSUE TITLE
[In WP] Le titre limite la place du contenu en dessous

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#204]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/organisms/hero/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
Dans ce cas, ce n'est pas le titre qui limite la taille du texte en-dessous, mais une règle css. Le texte peut faire, au maximum, 30% de la largeur totale, afin d'assurer que l'image soit visible. 

Ce composant est pensé pour des quantités de texte légère, afin d'introduire rapidement un sujet, et non de longs paragraphes.
