### ISSUE TITLE
[In WP] Dans une page faculty, la légende part en visite dans le header

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#205]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/content-types/faculty/#

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
même problème que précédemment: https://github.com/epfl-idevelop/elements/issues/207
