### ISSUE TITLE
[In WP] L'image est détaché du texte lorsque "on hover"

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#207]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/content-types/research-field/#

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
Cela arrive car le code du composant a été  directement injecté dans l'éditeur TinyMCe.
Des balises `<p>` sont ajoutées automatiquement par wordpress, ce qui corromp la structure de ce composant et son comportement.
voir: https://codex.wordpress.org/Function_Reference/wpautop
