### ISSUE TITLE
[In WP] Le breadcrump dans "Section" n'est pas à plat

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#208]
- Urls
	- https://migration-wp.epfl.ch/styleguide-qa/content-types/section/

- Versions
    - epfl-theme 0872446, Jul 17, 2018
    - elements v1.0.0

**Comment by knuch** [comment]
le code du breadcrumb doit être adapté dans le thème pour correspondre au nouveau markup (effet de bord du changement de design après la première intégration)

**Comment by zufrieden** [comment]
Moved here : https://github.com/antistatique/epfl-theme/issues/38
