### ISSUE TITLE
Hero shortcode icon

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#209]
We miss a png icon for the hero shortcode

**Comment by guillaumeberry** [comment]
@knuch this one?

![hero](https://user-images.githubusercontent.com/33514073/43823356-1766ec76-9aef-11e8-9c44-f7e2dddc06c8.png)

You also have the default one ✴️

![default](https://user-images.githubusercontent.com/33514073/43823391-2f716724-9aef-11e8-90e9-94432b97726e.png)

**Comment by guillaumeberry** [comment]
Resolved #231
