### ISSUE TITLE
"Nav async" : rendu asynchrone du menu

### ISSUE THREAD

**Issue by domq** [epfl-idevelop/elements#213]
En tant qu'administrateur du site,
- Je souhaite (dans certains cas à élucider à l'avenir) que la page Web ne connaisse pas d'avance l'entier du menu accessible dans le bouton «Browse»,
- De sorte à minimiser le temps de rendu initial de la page, sans péjorer les très grands menus.

En tant qu'utilisateur,
- Je veux être notifié du chargement asynchrone du menu,
- De sorte à ne pas être surpris ni par un délai, ni par une inactivité des contrôles pendant cette mise à jour

Cette fonction nécessite une infrastructure de rendu (JS + documentation CSS) largement indépendante des détails et du plan de transfert dynamique du contenu du menu (JSON vs. DOM, diverses stratégies de préfetch).

Dans le cas asynchrone, il est nécessaire : 
- de proposer un élément visuel représentant le chargement d'une partie du menu qui n'est pas encore connue du navigateur. Cet élément sera réalisé sous la forme d'appels JavaScript par ex : `spinnerOn()` et `spinnerOff()` — Pour la démo, un câblage en dur sur un simple événement de time-out d'une seconde (par ex.) sera suffisant
- de documenter les exigences de balisage du DOM pour qu'il soit rendu correctement par la ```<div style="overflow:hidden">``` du menu (classes `current-menu-ancestor` et `current-menu-parent` dans la version de ce jour du présent projet)

**Comment by zufrieden** [comment]
@domq bien vu 👍 !

Je propose d'avoir un loader dans le bouton plutot que de masquer la page derrière le voile blanc pendant l'attente. 

@domq une question : Est-ce que des niveaux du menu seront asynchrones ? Ou peut-on considérer qu'il n'y a qu'une requète au moment du clique sur le bouton "browse" ?

@pierre-georges 
- [ ] Avons-nous un design de loader ? (à check avec @guillaumeberry )
- [ ] L'endroit idéal selon moi et l'emplacement de l'icone dans le bouton browse

DEV CSS/JS : 
- [ ] Loader dans le bouton

**Comment by pierre-georges** [comment]
2 propositions pour ce loader:

1. Le mettre juste à côté du bouton "Browse".
2. Le mettre à l'intérieur, remplaçant l'icône pour garder exactement la même taille de bouton et ne pas avoir de petit "saut" de pixel.

https://invis.io/9DMZV08HJ6Z#/310515763_Breadcrumb_DAG

Spinner live: https://codepen.io/pierre_georges/pen/YjoWEv

**Comment by zufrieden** [comment]
Merci @pierre-georges 

On peut coder \o/
