### ISSUE TITLE
Détail événement

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#217]
## Goal
- Give the main information about an event

Example : [Kung Fu Motion](https://memento.epfl.ch/event/kung-fu-motion-les-archives-vivantes/)

Based on [Article-page](https://epfl-idevelop.github.io/elements/#/pages/article-page)
### Title
(Hero image if there is one)
### Event description 
- Text
- Meta informations (date, place, etc.)

## Open question @guillaumeberry @pierre-georges 
- Comment différencier les événements des articles (à part par le contenu) ?

**Comment by nsz** [comment]
@cfeuz est-ce que la structure et le contenu d'une page détail d'un événement te convienne ?

**Comment by cfeuz** [comment]
oui. Et pour répondre à la question de @guillaumeberry, la différence avec des articles, c'est qu'un événement est toujours lié à une date ou à une plage de date. 
Question ouverte: l'inscription est-elle prévue dans les meta informations ou y -a-til un bouton plus visible?

**Comment by frizzymagma** [comment]
@nsz Attention, à nouveau, comme il s'agit d'un outil 
--> 
Header light outil 
Pas de breadcrumb
Footer light

**Comment by guillaumeberry** [comment]
@frizzymagma @cfeuz @nsz 

Pour la différenciation actu / event, peut-être pour les events on peut mettre en avant les dates (cf. capture test ci-jointe avec une date en style H3).

![event](https://user-images.githubusercontent.com/33514073/43788206-262dc11c-9a6d-11e8-8f20-4d03990ad3aa.png)

**Comment by frizzymagma** [comment]
@guillaumeberry Questions qui me viennent immédiatement à l'esprit : 
1. Du coup, pour un utilisateur, il sera difficile de distinguer entre un événement et une actualité, right ? Est-ce qu'on veut ça ? 
2. Comme pour les actualités de l'outil actu.epfl.ch, le format/les proportions de l'image devrait être le/s même que les teasers correspondants (webservices repris sur des pages WP). Sinon, est-ce que les teasers vont redimensionner automatiquement les images principales mises sur les actualités / événements ?
3. Certaines informations sont importantes pour les événements et n'apparaissent pas du tout sur cette maquette : où se déroulera l'événement, à quels horaires a-t-il lieu, possibilité d'intégrer un programme de l'événement en question, qui organise, quelle est la personne de contact, est-ce que l'événement est ouvert à tous ou à un public restreint, est-ce que l'accès est sur inscription et où est-ce que les participants peuvent s'inscrire. 

Merci

**Comment by guillaumeberry** [comment]
@frizzymagma voici un début de réponses :

1. À priori, non on ne veut pas ça :P Du coup, nouvelle proposition (si ok avec @nsz @Yago )
Image 16:9 à 50% de large et definition list pour les infos sur l'événement
Speed maquette ci-jointe !
2. :Oui, tu as raison (l'erreur venait de ma super speed maquette précédente)
3. Encore une fois super speed maquette qui ne correspondait pas à la structure convenu avec Noémie 😉 

G.

![event-details-after](https://user-images.githubusercontent.com/33514073/43893678-15db98a2-9bd0-11e8-94f3-3ad13cba952d.png)

**Comment by frizzymagma** [comment]
Ah, merci speed @guillaumeberry ! 😉

**Comment by nsz** [comment]
@guillaumeberry @zufrieden 
Elle est publiée : https://epfl-idevelop.github.io/elements/#/pages/event-detail
Par contre il faudrait du code pour correspondre à ta version ci-dessus @guillaumeberry cc. @Yago

**Comment by zufrieden** [comment]
- [ ] Breadcrumb fixing visually @pierre-georges we need you

**Comment by frizzymagma** [comment]
Hello @zufrieden, voici le document envoyé la semaine dernière pour adapter le détail d'un événement dans memento.epfl.ch : 
[New layout - détail d'un événement.pdf](https://github.com/epfl-idevelop/elements/files/2328624/New.layout.-.detail.d.un.evenement.pdf)
