### ISSUE TITLE
Clean-up tag type

### ISSUE THREAD

**Issue by guillaumeberry** [epfl-idevelop/elements#218]
Too many tags on the dance floor!

We need to remove most of them, we keep:
- Plain
- Primary
- Secondary
- Light

We remove the rest, thanks,

Check with me if unclear ;)

**Comment by guillaumeberry** [comment]
This is what we keep:
![tags](https://user-images.githubusercontent.com/33514073/43704650-a74feddc-9960-11e8-9771-4feaa0a78457.png)

**Comment by knuch** [comment]
@8uhr test
