### ISSUE TITLE
Mettre 8uhr comme contributeur

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#219]
Nous avons besoin que @8uhr puisse éditer le repo et modifier les issues, pour effectuer ses tâches de gestion de projet. 

Merci !

(cc. @cfeuz @frizzymagma)

**Comment by lvenries** [comment]
@jdelasoie peux tu t'en occuper STP ?

**Comment by jdelasoie** [comment]
Ok, c'est fait !

**Comment by knuch** [comment]
merci beaucoup!
