### ISSUE TITLE
Page de résultats de recherche d'une personne

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#222]
## Goal
- List people who match the search

### People list
Component : [Contact block listing](https://github.com/epfl-idevelop/elements/issues/156) (need component - issue open)

**Comment by frizzymagma** [comment]
@nsz Il ne s'agit pas de WordPress mais d'un outil séparé. 

Header --> Header light outil
Pas de breadcrumb
Footer light

**Comment by nsz** [comment]
@guillaumeberry @zufrieden publié, ready to review : https://epfl-idevelop.github.io/elements/#/pages/people-list

**Comment by zufrieden** [comment]
@frizzymagma pour nous, le breadcrumb doit être présent partout.
le browse uniquement dans le [www.epfl.ch/*]

**Comment by zufrieden** [comment]
Review done + change header to light version
@frizzymagma you'll be able to check on the next release
