### ISSUE TITLE
People - page de profil d'une personne

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#224]
Retour sur la proposition de page de profil people : https://epfl-idevelop.github.io/elements/#/pages/people-page

Comparaison avec la proposition de :ratio qui nous paraît plus aboutie : https://test-people.epfl.ch/ergo/#!

- Header light outil 
- Titre (nom de la personne)
- Photo de profil --> s'il n'y a pas de photo affichée, mettre un picto prétexte avec p.ex. une ombre

![capture d ecran 2018-08-07 a 12 23 49](https://user-images.githubusercontent.com/33958302/43770574-16e0b24e-9a3d-11e8-80b3-d99fe72977d4.png)

1. Attention à la longueur du titre
2. Attention à la longueur des boutons : adresse email, URL site web et numéro de téléphone
3. Il faut discerner la fonction et le rattachement. Comment présenter cela visuellement ? (attention, il peut y avoir plusieurs fonctions et rattachements pour une personne : ex. https://people.epfl.ch/edouard.bugnion?lang=fr )
4. Dans le corps, comment seront présentées les adresses + liens ? 
5. Cette partie-là est beaucoup trop visible par rapport au reste. Comment les informations contenues dans ce "toggle" seront représentées ? 

Autres commentaires : 

- Les liens/ancres "Biography", "Publications", "Teaching & PhD" ne fonctionnent pas
- Il manque les cours en bas de page (ex. https://test-people.epfl.ch/ergo/#!) 
- Il manque les liens vers les réseaux sociaux de la personne

- Footer light
- Pas de sidebar

**Comment by pierre-georges** [comment]
Concernant le point 5, est-ce qu'on affiche ces informations dans une autre page comme c'est le cas aujourd'hui ? Ou est-il souhaité aujourd'hui de réunir tout sur une même page ?

Pour le reste, j'ai fais quelques modifications de la maquette:
https://invis.io/9DMZV08HJ6Z#/314778291_People_A

**Comment by frizzymagma** [comment]
@zufrieden Hello, est-ce qu'il y a une adaptation de prévue de la page https://epfl-idevelop.github.io/elements/#/pages/people-detail ? 

Nous devons être en mesure de donner quelque chose d'abouti au développeur chargé de l'adaptation de l'outil people.epfl.ch et ce n'est pas le cas actuellement. Nous avons une grosse pression de la part de la hiérarchie pour adapter l'outil People, d'autant plus que la maquette fonctionnelle proposée par :ratio date de janvier 2018 ! (cf. https://3.basecamp.com/3096442/buckets/5137241/todos/861250888) 

Merci de nous fournir une réponse rapidement.

**Comment by zufrieden** [comment]
Merci de valider le design ;-) @frizzymagma

**Comment by zufrieden** [comment]
![peopledetail-fullpage](https://user-images.githubusercontent.com/451236/45028263-a6f2e100-b044-11e8-92e6-cdbf0c103b39.png)
