### ISSUE TITLE
Collapse - question about component in styleguide

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#225]
![capture d ecran 2018-08-07 a 15 40 51](https://user-images.githubusercontent.com/33958302/43779322-6c1ee422-9a58-11e8-8127-29a2c0bd2154.png)

Quelle différence entre un bouton avec lien derrière et le premier élément "collapse content" qui va ouvrir du contenu pour un utilisateur ?

**Comment by guillaumeberry** [comment]
@frizzymagma je regarde avec Yann si on utilise ce composant et si on le garde.

**Comment by guillaumeberry** [comment]
@frizzymagma Vu avec Yann et Flavien. Composant non utilisé : on le retire de la prochaine publication.
