### ISSUE TITLE
Dropdown - comment about component in styleguide

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#226]
![capture d ecran 2018-08-07 a 15 46 03](https://user-images.githubusercontent.com/33958302/43779605-1019d758-9a59-11e8-8a51-b47cbdadc635.png)

There seems to be a slight display issue of this component (bottom of dropdown doesn't appear). 
All seems fine in the "view full render" mode though.

**Comment by zufrieden** [comment]
If full render is correct. We're covered.
