### ISSUE TITLE
Social icons - round and disrete - round not applied

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#228]
![capture d ecran 2018-08-07 a 16 08 00](https://user-images.githubusercontent.com/33958302/43780999-36f1cc48-9a5c-11e8-8552-93d68b6537d7.png)

In the styleguide, the "round discrete" link appears to be square.

**Comment by zufrieden** [comment]
Atom -> https://epfl-idevelop.github.io/elements/#/atoms/social-icon

- [ ] Round Discrete Link should actually be round ;-)
