### ISSUE TITLE
Science-Question Content-types - Add title

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#229]
![capture d ecran 2018-08-07 a 16 22 13](https://user-images.githubusercontent.com/33958302/43781802-0f1994a6-9a5e-11e8-83d3-7afdfd65d8ea.png)

Shouldn't there be a "vote" button here? 

It would be better to call this component "Science question", and also add it as a title in the component ("Question de science" in French), so that it would appear each time someone use it. Thank you.

**Comment by zufrieden** [comment]
- [ ] Add a title in the component "Question de science"

https://epfl-idevelop.github.io/elements/#/content-types/science-question

**Comment by pierre-georges** [comment]
Here:
https://invis.io/9DMZV08HJ6Z#/279353739_Science-Question
