### ISSUE TITLE
Bachelor project content-type - Remove Avatar

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#230]
![capture d ecran 2018-08-07 a 16 43 38](https://user-images.githubusercontent.com/33958302/43783054-0de6c7c2-9a61-11e8-9e64-7d48368e9f82.png)

As previously asked: there is no need to put any people picture nor name in this component. 
Also, please only indicate "Bachelor", and no "> BioS". 

Thanks.

**Comment by zufrieden** [comment]
https://epfl-idevelop.github.io/elements/#/content-types/bachelor-project
- [ ] Remove Avatar (image and title)
- [ ] Remove card-info second level (in the exemple) but let the ability to have a path
