### ISSUE TITLE
Question de science

### ISSUE THREAD

**Issue by nsz** [epfl-idevelop/elements#240]
[Example](https://qi.epfl.ch/question/)

## Goal
educate / give scientific information to the public

### Graphic 
<img width="486" alt="capture d ecran 2018-08-30 a 14 37 16" src="https://user-images.githubusercontent.com/1941982/44851948-3887da80-ac62-11e8-9fd1-a394c35cfd22.png">

@frizzymagma est-ce nécessaire de faire un composant pour les graphiques ou est-ce que vous utiliserez le système actuel ? cc. @zufrieden 

### [Footer](https://epfl-idevelop.github.io/elements/#/organisms/footer)

**Comment by zufrieden** [comment]
Plus nécessaire de faire cette page.
Validé par @frizzymagma
