### ISSUE TITLE
WordPress - Breadcrumb

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#246]
Dans la dernière version du thème WP EPFL (1.0.0.), le breadcrumb ne s'affiche pas du tout. Seule l'icône de la maison s'affiche. Rien d'autre. 

![capture d ecran 2018-08-14 a 11 18 27](https://user-images.githubusercontent.com/33958302/44083359-0eca14d4-9fb4-11e8-91b7-abbdd38824f6.png)

**Comment by zufrieden** [comment]
Moved to wordpress theme repository https://github.com/antistatique/epfl-theme/issues/38
