### ISSUE TITLE
WordPress - Homepage EPFL

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#247]
Le titre s'affiche sur la homepage EPFL alors qu'il ne devrait pas y avoir de titre. 

![capture d ecran 2018-08-14 a 11 22 37](https://user-images.githubusercontent.com/33958302/44083556-94673536-9fb4-11e8-99f1-1acf9ee747f5.png)

**Comment by zufrieden** [comment]
--> Moved the issue to https://github.com/antistatique/epfl-theme/issues/39
