### ISSUE TITLE
[In WP] Hidden title (homepage, page with hero element, etc.)

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#248]
[Edit] Ok, I've found how to hide a title. But it doesn't look good. 

I'm not sure that simply erasing the title of the page is a good idea. How can we do it differenlty, and better. 

When a page title is hidden: 
- the title in navigation doesn't appear. How to change that? 
- the blank space at the top should be reduced

![capture d ecran 2018-08-16 a 15 57 50](https://user-images.githubusercontent.com/33958302/44213129-4ff89b00-a16d-11e8-8345-7dc4f00d42df.png)

Clearly, this is not the best way. Can you help?

**Comment by zufrieden** [comment]
Fixed with https://github.com/epfl-idevelop/wp-theme-2018/pull/63
