### ISSUE TITLE
[In WP] Blank space when 2 consecutive grey backgrounds

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#249]
A blank space appears when 2 components with grey backgrounds are used consecutively. 

Solution: reduce space between 2 components.

![capture d ecran 2018-08-16 a 09 35 58](https://user-images.githubusercontent.com/33958302/44195001-06da2400-a138-11e8-9cc1-1915ff792546.png)

**Comment by zufrieden** [comment]
add into layout.scss logic to avoid margin when consecutive container full with bg-gray-100

**Comment by zufrieden** [comment]
Fixed ;-)
