### ISSUE TITLE
[In WP] We need custom shortcodes to use enough elements

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#250]
We need "custom" shortcode for the following components : 
- Page highlight
- Page teaser
- Post highlight
- Post teaser

At the moment, they are not usable, and we need to insert custom content manually. 

![capture d ecran 2018-08-14 a 11 07 20](https://user-images.githubusercontent.com/33958302/44195020-148fa980-a138-11e8-90ed-35b536dad845.png)

**Comment by zufrieden** [comment]
Those components already exist in custom format
