### ISSUE TITLE
Pictures elements - captions and copyrights

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#251]
We need to have captions and copyright indicated with pictures inserted in a page: eg. with hero element, highlighted teaser, cover picture, half-desktop pictures, etc. 

![capture d ecran 2018-08-16 a 09 47 17](https://user-images.githubusercontent.com/33958302/44195463-6b49b300-a139-11e8-8846-5cc3b2330bc0.png)

**Comment by frizzymagma** [comment]
@zufrieden  FYI, the component Hero still doesn't have the caption indicated in the picture : https://epfl-idevelop.github.io/elements/#/organisms/hero

**Comment by frizzymagma** [comment]
@zufrieden Merci d'avoir corrigé le custom teaser, par contre, sur le composant Hero, il manque toujours les informations concernant l'image. Merci de corriger.

**Comment by zufrieden** [comment]
Donc, nous n'avions pas prévu de légende spécifique pour les hero-image. Pas vraiment un bug mais j'ai fait la modification ;-)
https://github.com/epfl-idevelop/elements/pull/324
