### ISSUE TITLE
[Component] Problème d'affichage custom highlight

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#252]
Quelques petits soucis d'affichage pour le composant "custom highlight" une fois redimensionné : 
![capture d ecran 2018-08-16 a 09 47 17](https://user-images.githubusercontent.com/33958302/44196878-77377400-a13d-11e8-8aa9-816c90cf6cbf.png)

(via desktop, navigateur Firefox)

**Comment by zufrieden** [comment]
This is related to WP implementation of custome hightlight using img-fluid.
Removing it and sizes solve the issue
https://github.com/epfl-idevelop/wp-theme-2018/blob/dev/shortcodes/custom_highlight/view.php#L19

Not sure why we added it in the first place @knuch ?

**Comment by frizzymagma** [comment]
![capture d ecran 2018-08-28 a 14 55 14](https://user-images.githubusercontent.com/33958302/44724245-6c33fa80-aad2-11e8-9f15-22a7cf711b88.png)

**Comment by zufrieden** [comment]
Remove "An image description" https://github.com/epfl-idevelop/wp-theme-2018/blob/dev/shortcodes/custom_highlight/view.php#L22
And implement popover with actual legend instead ;-)

**Comment by zufrieden** [comment]
Fixed here https://github.com/epfl-idevelop/wp-theme-2018/pull/71
