### ISSUE TITLE
[In WP] Alignement des cartes

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#254]
La logique d'affichage pour 1, 2 ou 3 cartes, présentée sur https://epfl-idevelop.github.io/elements/#/molecules/card-deck n'est pas reproduite dans le thème WP. 

![capture d ecran 2018-08-17 a 11 01 17](https://user-images.githubusercontent.com/33958302/44257652-f778da80-a20c-11e8-86da-750b78c9e50e.png)

**Comment by frizzymagma** [comment]
![capture d ecran 2018-08-28 a 15 01 15](https://user-images.githubusercontent.com/33958302/44724525-3e02ea80-aad3-11e8-9145-2dfd4a36e963.png)

**Comment by zufrieden** [comment]
--> https://github.com/epfl-idevelop/wp-theme-2018/issues/54

**Comment by zufrieden** [comment]
Corrigé. Reste encore la question des titres
