### ISSUE TITLE
[In WP] Mettre acronymes en exposant

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#255]
Pourriez-vous nous indiquer comment mettre en exposant, dans les divers titres, les divers acronymes, comme il avait été validé via les maquettes (cf. captures d'écran). Merci.

![capture d ecran 2018-08-17 a 11 53 08](https://user-images.githubusercontent.com/33958302/44260263-2b0b3300-a214-11e8-8679-4f6e0327af9d.png)

![capture d ecran 2018-08-17 a 11 54 45](https://user-images.githubusercontent.com/33958302/44260369-7c1b2700-a214-11e8-87bd-c763f1374fd2.png)

![capture d ecran 2018-08-17 a 11 54 59](https://user-images.githubusercontent.com/33958302/44260370-7c1b2700-a214-11e8-9a0e-b77aac2c5889.png)

**Comment by zufrieden** [comment]
Dans l'utilisation du shortcode si les champs ne sont pas parsés, il est possible d'ajouter : 
<sup>ABCD</sup>

![screenshot 2018-09-04 09 40 49](https://user-images.githubusercontent.com/451236/45017007-b3684100-b026-11e8-827c-2834845a636d.png)
![screenshot 2018-09-04 09 40 34](https://user-images.githubusercontent.com/451236/45017008-b3684100-b026-11e8-86f7-2d770d500450.png)
