### ISSUE TITLE
Espacement horizontal entre les cellules des tableaux

### ISSUE THREAD

**Issue by LeBenLeBen** [epfl-idevelop/elements#256]
Lorsque le contenu des tableaux est dense, il devient difficile de discerner les différentes colonnes à cause du manque de padding horizontal entre les cellules.

![capture d ecran 2018-08-17 a 15 45 29](https://user-images.githubusercontent.com/793344/44269458-de841f80-a234-11e8-8104-981a07e3a3ac.png)

**Comment by Yago** [comment]
🤔 Hmmm, I not sure if you are using the right component for this case...

The [`contact bloc` or the `contact bloc compact`](https://epfl-idevelop.github.io/elements/#/organisms/contact) doesn't use tables, but **definition lists** to present people's metadata. I hope it will fit to your needs 😉 

Thanks for you contribution !
