### ISSUE TITLE
Le focus ring des boutons crée un scroll horizontal dans la page

### ISSUE THREAD

**Issue by LeBenLeBen** [epfl-idevelop/elements#257]
Lorsqu'un bouton pleine largeur est utilisé à la racine d'un container, celui-ci génère un scroll horizontal dans la page. Cela semble venir du pseudo-element before (marqué en rouge dans l'exemple ci-dessous) qui se retrouve être plus large que l'écran.

![capture d ecran - 2018-08-17 a 16 45 55](https://user-images.githubusercontent.com/793344/44272507-535b5780-a23d-11e8-861f-3b13a568267e.png)

L'écart est très faible, quelques pixels uniquement, mais suffisant pour activer le scroll horizontal. On le voit sur la capture ci-dessus, la marge blanche est plus large à droite qu'à gauche.

**Comment by zufrieden** [comment]
https://search.epfl.ch/?q=development to get a better sense of what's happening ;-) @Yago

**Comment by Yago** [comment]
We must sort the pseudo element of the document's flow to prevent it from adding those horizontal scrollbars.

Thanks for reporting it 😉
