### ISSUE TITLE
[In WP] Pictures alignment ant text (problem!)

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#266]
There is obviously a problem when we insert images and we try to align text just next to it. It only show 1 lign text next to the image, and always on the right side of the inserted image. 
See screenshots. 

![capture d ecran 2018-08-23 a 15 41 51](https://user-images.githubusercontent.com/33958302/44530099-f6a0e680-a6ed-11e8-9e98-9c9818c3e334.png)
![capture d ecran 2018-08-23 a 15 42 05](https://user-images.githubusercontent.com/33958302/44530104-f9034080-a6ed-11e8-9f8f-2640d5b39270.png)

![capture d ecran 2018-08-23 a 15 42 22](https://user-images.githubusercontent.com/33958302/44530106-fb659a80-a6ed-11e8-8e6f-feb2a8420261.png)
![capture d ecran 2018-08-23 a 15 42 42](https://user-images.githubusercontent.com/33958302/44530113-fe608b00-a6ed-11e8-9175-a2211ace2889.png)

**Comment by zufrieden** [comment]
Malheureusement, ce n'est pas si simple à corriger.
Nous avons implémenté le système de container et de grille à l'aide de Grid CSS pour nous permettre la souplesse d'avoir des shortcodes qui puisse prendre plusieurs largeurs.
Ainsi tous les éléments autres respectent la largeur du container. Que ce soit une image, un paragraphe, une liste, un tableau etc.
Un PR est en cours mais ne fonctionne pas https://github.com/epfl-idevelop/wp-theme-2018/pull/75

À noter que le design ne prévoit pas ce type d'alignement ...

**Comment by frizzymagma** [comment]
@zufrieden Pour nous, c'est un bug. Ça ne va pas et il faut trouver une solution.

**Comment by frizzymagma** [comment]
@zufrieden Suite à une discussion avec @lvenries nous allons soumettre aux utilisateurs les recommandations suivantes : 
- soit l'image insérée prend la largeur de la colonne centrale par défaut (d'ailleurs question : quelle est la largeur de cette colonne ?)
- soit l'image est plus petite que la largeur de la colonne centrale, et le texte s'affiche avant + après l'image. 

Par la suite, un shortcode sera créé pour répondre au besoin des utilisateurs d'afficher du texte à côté d'une image.

**Comment by knuch** [comment]
@frizzymagma la taille de la colonne varie selon la taille de l'écran, et prends les dimensions suivantes:

- **sm**: 540px
- **md**: 600px
- **lg**: 640px
- **xl**: 570px (elle diminue un peu ici car elle doit compter qu'une colonne apparaît à gauche et donc laisser de l'espace au texte pour respirer

Si vous dites à vos utilisateurs d'utiliser des images de minimum 640px de large, vous serez tout à fait tranquille.

Si ils veulent un rendu précis de l'image sur tous les écrans retina (macbooks,  smartphones, etc),  doublez ce chiffre --> 1280px. Mais à partir du moment où l'image fera 640px, elle sera affichée en pleine largeur de colonne.

**Comment by frizzymagma** [comment]
@knuch Super ! merci pour cette réponse complète 😃
