### ISSUE TITLE
Faculty --> School rename component 

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#271]
1. We urgently need to be able to insert at least 8 components "Faculties"! (only 7 maximum possible at the moment)

2. We need to change the name of this component in the shortcode but also in the Styleguide: Faculty --> School 

Thank you.

![capture d ecran 2018-08-27 a 15 55 55](https://user-images.githubusercontent.com/33958302/44663813-d9cc2200-aa11-11e8-8aa3-91939d283003.png)
![capture d ecran 2018-08-27 a 15 56 02](https://user-images.githubusercontent.com/33958302/44663814-d9cc2200-aa11-11e8-8be2-cd1af5971f0c.png)

**Comment by zufrieden** [comment]
- [ ] WP https://github.com/epfl-idevelop/wp-theme-2018/blob/dev/shortcodes/faculties/shortcake.php#L10 replace 7 by 8

**Comment by zufrieden** [comment]
10 :-)

**Comment by zufrieden** [comment]
- [ ] Still need to rename the component from : faculty to school
