### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#272]
https://github.com/epfl-idevelop/elements/releases/tag/1.2.0

Prêt à être intégré dans le thème WP

**Comment by frizzymagma** [comment]
Hello @zufrieden, merci pour l'info. 
Nous observons encore pas mal de problème dont : 

- Il manque toujours l'icône de la loupe (pour le champ "recherche") dans le header
- La navigation ne fonctionne pas (lorsqu'on clique sur "Browse", seules de lignes apparaissent)
- Le breadcrumb ne s'affiche pas (sauf l'icône de la maison)
- Les éléments sensés prendre tout l'écran ne prennent plus qu'une partie (cf. capture d'écran)

![capture d ecran 2018-08-28 a 10 05 06](https://user-images.githubusercontent.com/33958302/44709626-60ccd900-aaaa-11e8-8260-f41a43b465c5.png)

**Comment by zufrieden** [comment]
Search --> #42 

pour le composant full largeur, effectivement je n'arrive pas à reproduire le bug.
