### ISSUE TITLE
[3-6] Composant contact - compact - pour les listing

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#274]
![screenshot 2018-08-28 14 30 13](https://user-images.githubusercontent.com/451236/44722958-0003c780-aacf-11e8-9e92-4e8d747a03c5.png)

**Comment by pierre-georges** [comment]
@zufrieden voila :)
https://projects.invisionapp.com/share/9DMZV08HJ6Z#/screens/295830528_Contact_-_Listing

**Comment by zufrieden** [comment]
![screenshot 2018-09-11 10 00 14](https://user-images.githubusercontent.com/451236/45346457-89c09400-b5a9-11e8-8341-57b9d6bf28fd.png)

**Comment by zufrieden** [comment]
@frizzymagma merci pour ton feedback

**Comment by frizzymagma** [comment]
@lvenries ça te convient ? :-)

**Comment by lvenries** [comment]
Oui je pense que c'est bien et que cela va répondre à un besoin de plusieurs sites.
IL faut peut-être faire valider par Ion. Je te laisse voir  @frizzymagma

**Comment by zufrieden** [comment]
- [ ] Ajouter une photo placeholder dans la liste (une des personne n'a pas de photo https://epfl-idevelop.github.io/elements/svg/avatar-placeholder.svg)
- [ ] Version small works with css grid only :-P

**Comment by frizzymagma** [comment]
@zufrieden Hello, où est-ce que vous en êtes ? A quelle date est-ce que ce composant sera implémenté dans le styleguide ? Merci.
