### ISSUE TITLE
[1.5]Add alerts with actions button (1 parimary button, 1 secondary) fixed on top (cookie consent use case)

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#296]
- [x] Design it ;-)
- [ ] Code it

**Comment by zufrieden** [comment]
Today's design

![screenshot 2018-09-12 13 33 50](https://user-images.githubusercontent.com/451236/45422458-87853500-b690-11e8-893d-3305fee69008.png)

**Comment by pierre-georges** [comment]
Desktop + mobile
https://invis.io/9DMZV08HJ6Z#/294364103_Alerts

**Comment by zufrieden** [comment]
Merci @pierre-georges 

![screenshot 2018-09-12 17 34 01](https://user-images.githubusercontent.com/451236/45435992-0f2f6b80-b6b2-11e8-915a-f0fecf197408.png)
![screenshot 2018-09-12 17 33 58](https://user-images.githubusercontent.com/451236/45435993-0f2f6b80-b6b2-11e8-9672-4cd068867301.png)

- [ ] Position fixed

@knuch n'hésite pas à checker en live avec @pierre-georges au moment de l'intégration.
