### ISSUE TITLE
[2] Header light - logo disappear on mobile

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#298]
- [x] Logo sould be there on mobile
- [ ] Find a design solution to have site-title displayed

- [ ] Remove margin-left 20px to align logo and breacrumb when header-light.

**Comment by zufrieden** [comment]
![epfl_logo_headerlight](https://user-images.githubusercontent.com/451236/45421509-8d2d4b80-b68d-11e8-8dd2-7483205a061c.gif)

**Comment by frizzymagma** [comment]
@zufrieden Est-ce que ça a été corrigé ? Merci.
