### ISSUE TITLE
Image pour "quote"

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-idevelop/elements#301]
L'image de l'élément quote semble un peu trop petite : 

![screenshot from 2018-09-13 18-04-51](https://user-images.githubusercontent.com/4997224/45500791-c6de7f00-b77f-11e8-936a-2e87d8f34eb4.png)

Et si l'image uploadée n'est pas carré, l'image affichée n'est pas "ronde" mais cela est peut être normale.

**Comment by frizzymagma** [comment]
@zufrieden c'est considéré comme un bug, non?

**Comment by zufrieden** [comment]
Non, pour avoir une image dans un rond, il faut la servir avec des tailles carrées ;-)
Mais l'info manquait dans la doc, ce qui est corrigé.
