### ISSUE TITLE
People detail page adjustements

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/elements#302]
- [x] Export HTML easily ?
- [ ] Anchor navigation isn't working (clicking)

**Comment by frizzymagma** [comment]
@zufrieden Est-ce que c'est toujours d'actualité, suite à la discussion avec Ion (dév de people.epfl.ch) ?

**Comment by knuch** [comment]
@zufrieden après test il semblerait que le problème des liens anchor soient liés à l'utilisation de React-Router V4 dans toolbox. 

J'ai mis un fix en place sur elements pour répliquer le comportement. J'ai testé sur deux installs de wordpress et les anchor link marchent correctement en utilisant le markup de la page people 😄

**Comment by zufrieden** [comment]
@knuch 
Je te confirme, on nous a juste fait remarqué que ça ne fonctionnait pas dans la démo du styleguide
