### ISSUE TITLE
[Thème WP] Affichage information dans un Post

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#305]
Hello, 
Les dates de publication et de modification s'affichent côte-à-côte lorsqu'on crée un poste. 

![capture d ecran 2018-09-27 a 16 20 10](https://user-images.githubusercontent.com/33958302/46153765-1343b780-c274-11e8-897b-4f867dd09b54.png)

**Comment by zufrieden** [comment]
Nécessaire de ne garder que la date de publication du coup ?

**Comment by frizzymagma** [comment]
Oui merci.

**Comment by zufrieden** [comment]
--> Correction à faire dans le thème https://github.com/epfl-idevelop/wp-theme-2018/issues/117
