### ISSUE TITLE
Shortcode "Post teaser"

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#306]
Une fois activée, la case «gray background» insère un post vide en première position.

**Comment by zufrieden** [comment]
Merci, effectivement, l'erreur vient de cette ligne https://github.com/epfl-idevelop/wp-theme-2018/blob/dev/shortcodes/post_teaser/view.php#L7
Il s'agit d'un bug dans le thème WP
--> https://github.com/epfl-idevelop/wp-theme-2018/issues/111
