### ISSUE TITLE
Shortcode Toggle

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#307]
Il n'est pas possible d'avoir deux shortcode toggle dans la même page, car ceux-ci rentrent en conflit. 

Actuellement, le shortcode permet d'insérer 10 items.

**Comment by zufrieden** [comment]
Le choix de la technologie "shortcode" shortcake ne permettant pas d'ajout d'élément de liste dynamique, nous avons limité à 10 éléments.

Je n'ai pas de conflit avec 2 shortcode toggle comme testé sur cette page http://epfl.alwaysdata.net/accueil/shortcodes/collapsable/

**Comment by frizzymagma** [comment]
@lvenries m'informe que ce problème est résolu.
