### ISSUE TITLE
Shortcode "Custom teaser"

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#308]
Le fait d'afficher "Section title" ou encore un bouton par défaut avec "See more" dans les éléments titre et label non renseignés du shortcode custom teaser pose beaucoup de problèmes. 

Si un champ n'est pas renseigner, il ne faudrait pas du tout afficher l'élément. 

![capture d ecran 2018-09-27 a 16 49 41](https://user-images.githubusercontent.com/33958302/46154400-5eaa9580-c275-11e8-9cf3-e33eaa0ff6fe.png)

**Comment by zufrieden** [comment]
Il s'agit d'une amélioration du shortcode dans le thème wordpress
https://github.com/epfl-idevelop/wp-theme-2018/issues/109
