### ISSUE TITLE
Checkbox bad vertical alignment

### ISSUE THREAD

**Issue by obieler** [epfl-idevelop/elements#314]
La case à cocher n'est pas bien centrée verticalement dans le div, le label non plus:

![screenshot from 2018-10-05 14-13-42](https://user-images.githubusercontent.com/24526380/46535062-88ce0a00-c8aa-11e8-8978-57972b61635a.png)

https://epfl-idevelop.github.io/elements/#/atoms/checkbox

**Comment by zufrieden** [comment]
Merci. Effectivement, il y a un problème d'alignement.
