### ISSUE TITLE
Affichage largeur contenu

### ISSUE THREAD

**Issue by frizzymagma** [epfl-idevelop/elements#315]
Nous avons des cas où le contenu s'affiche parfois sur une colonne beaucoup plus grande que celle prévue de base (cf. capture d'écran). 

![capture d ecran 2018-10-08 a 11 47 19](https://user-images.githubusercontent.com/33958302/46602304-10f12100-caf0-11e8-811f-50106267cf28.png)
![capture d ecran 2018-10-08 a 11 47 28](https://user-images.githubusercontent.com/33958302/46602305-10f12100-caf0-11e8-8f2a-baa35d3e8f26.png)

**Comment by zufrieden** [comment]
Merci pour le feedback @frizzymagma 
Est-ce que je pourrais avoir accès à la page en question et savoir quel paramétrage a été effectué sur l'image. Car sur l'instance de test, même en forçant une largeur plus grande à l'image je n'arrive pas à reproduire ce comportement.

**Comment by frizzymagma** [comment]
Je suis désolée, je ne sais pas comment vous donner accès à  https://www2018.epfl.ch/schools/enac/education/architecture/bachelor/ ‎  (@lvenries c'est possible ou pas ? )

![capture d ecran 2018-10-09 a 16 01 04](https://user-images.githubusercontent.com/33958302/46674571-c13c5380-cbdc-11e8-862e-af5437b3e787.png)
![capture d ecran 2018-10-09 a 16 01 11](https://user-images.githubusercontent.com/33958302/46674572-c13c5380-cbdc-11e8-9b97-6c48c1ac4b0f.png)
![capture d ecran 2018-10-09 a 16 02 21](https://user-images.githubusercontent.com/33958302/46674573-c13c5380-cbdc-11e8-800f-06b82f7b2a6e.png)

**Comment by lvenries** [comment]
@zufrieden , tu n'es pas accrédité à l'EPFL et je ne peux pas donc pas te donner des droits.
J'ai donné des droits aux comptes de Flavien et Yann. Il faut utiliser leur compte.

**Comment by frizzymagma** [comment]
@zufrieden Nous avons besoin d'avoir la taille de la largeur de cette "colonne centrale". Pourriez-vous nous l'indiquer ? 
Aussi, si vous aviez sous le coude les références concernant la recommandation scientifiquement prouvée pour cette largeur de colonne, ça nous aiderait bien également. 😃 Merci!

**Comment by knuch** [comment]
@frizzymagma merci pour le lien!

J'ai pu adapter le code de la grille pour nous assurer que la largeur de colonne ne soit pas impactée quand un élément non prévu prends plus de place que prévu. ça sera dans la release de elements que je vais faire ce soir. 

sinon pour votre problème précis, le souci est que cette image est encapsulée dans des tags HTML non prévus, et que donc elle ne se fait pas affecter par les règles que j'ai définie pour les alignement d'images. 

**Code actuel:**
<div class="legende">
   <div class="description">
      <img class="alignnone wp-image-2887" src="https://www2018.epfl.ch/schools/enac/wp-content/uploads/2018/10/Graphique_fr-300x99.png" alt="" width="949" height="313" />
   </div>
</div>```

**Code correct:**
```<img class="alignnone wp-image-2887" src="https://www2018.epfl.ch/schools/enac/wp-content/uploads/2018/10/Graphique_fr-300x99.png" alt="" width="949" height="313" />
```

selon moi ce html supplémentaire peut provenir de deux sources:

1. Il s'agit d'un copier-collé dans l'éditeur qui a embarqué avec lui des éléments HTML indésirables
2. Il s'agit du résultat d'un export

**Comment by knuch** [comment]
@frizzymagma de rien 😄 si jamais dès ce soir le comportement sera le suivant dans le cas de figure où une image n'est pas formatée comme prévu:
- la colonne garde la même largeur
- l'image, si elle est trop grande, dépassera du contenu et de l'écran

comme présenté ici:
<img width="1262" alt="capture d ecran 2018-10-19 a 10 30 09" src="https://user-images.githubusercontent.com/4548432/47206858-ff2e3a00-d389-11e8-9900-76c86849d6f5.png">

**Comment by zufrieden** [comment]
@frizzymagma 
Concernant les publications sur le nombre de caractères par ligne, voici quelques liens qui appuient nos propos.

— https://en.wikipedia.org/wiki/Line_length
— http://mikeyanderson.com/optimal_characters_per_line
— https://practicaltypography.com/line-length.html
— http://web.mit.edu/6.813/www/sp17/classes/16-typography/#whitespace
Pour aller plus loin :
— https://alistapart.com/article/how-we-read
— https://en.wikipedia.org/wiki/Eye_movement_in_reading#Saccades

@guillaumeberry en discute avec toi si besoin ;-)
