### ISSUE TITLE
Mission teaser - molecule

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#32]
[invision](https://projects.invisionapp.com/share/N4FDSKWX8ZB#/screens/279353737_Teaser-Mission)

**validated variants:**

- [ ] faculty

- [ ] laboratory

- [ ] reasearch field

- [ ] research project

- [ ] training

- [ ] association

- [ ] program

**Comment by Yago** [comment]
on it 👍

**Comment by Yago** [comment]
Not ready, design must be rethinked
