### ISSUE TITLE
Post teaser, élément en trop

### ISSUE THREAD

**Issue by dingepfl** [epfl-idevelop/elements#320]
Bonjour,

Dans les _Post teasers_, quand l'option "Gray Background" est sélectionnée, cela ajoute un cadre blanc en trop (cela en met 2 quand un seul article est indiqué, 3 quand 2 sont indiqués et 4 quand les 3 sont indiqués):

![postteasersbackgroundgrisconfig](https://user-images.githubusercontent.com/36680622/46953065-00f7b500-d08d-11e8-9ba6-ec3926ee6d74.png)

![postteasersbackgroundgris](https://user-images.githubusercontent.com/36680622/46953067-00f7b500-d08d-11e8-96bb-673a4f56af7a.png)

Le bug ne se présente pas quand l'option est déactivée

**Comment by zufrieden** [comment]
Merci, déjà relevé ici
https://github.com/epfl-idevelop/elements/issues/306
et l'issue concerne le thème WP ici https://github.com/epfl-idevelop/wp-theme-2018/issues/111
