### ISSUE TITLE
[1] Post teaser, taille d'image trop petite

### ISSUE THREAD

**Issue by dingepfl** [epfl-idevelop/elements#321]
Bonjour,

Pour les _Post teasers_, quand deux articles sont indiqués, la taille de la deuxième image est un peu plus petite verticalement (tout le cadre de la deuxième image semble être plus étroit) que l'autre.

![postteaser2articles](https://user-images.githubusercontent.com/36680622/46953327-dc500d00-d08d-11e8-9f37-fbe1832b785f.png)

![postteaser2articlesexemple](https://user-images.githubusercontent.com/36680622/46953326-dc500d00-d08d-11e8-9c43-6253df3b728d.png)

La taille des images est uniforme quand 3 articles sont sélectionnés

**Comment by zufrieden** [comment]
- [ ] Déterminé si c'est lié au WP ou au CSS
