### ISSUE TITLE
Différence de comportement entre www2018.epfl.ch et epfl.alwaysdata.net

### ISSUE THREAD

**Issue by dingepfl** [epfl-idevelop/elements#322]
Bonjour,

En voulant recréer la documentation fournie pour la mettre à disposition de nos utilisateurs, nous avons constaté une différence de comportement entre les deux instances:

Sur http://epfl.alwaysdata.net/accueil/shortcodes/ , le texte qui se trouve dans des balises HTML est ignoré par les page teasers:

![pageteasersalwaysdata](https://user-images.githubusercontent.com/36680622/46954548-330b1600-d091-11e8-94e2-fabe6933c7ec.png)
![alwaysdatahtml](https://user-images.githubusercontent.com/36680622/46954549-330b1600-d091-11e8-877f-da84c6222ddf.png)

Mais sur notre site https://www2018.epfl.ch/campus/services/fr/accueil/communication/materiel-et-ressources/charte-graphique-web/elements-et-shortcodes/ tous les éléments sont repris:

![bugwww2018](https://user-images.githubusercontent.com/36680622/46954662-74032a80-d091-11e8-873f-84a5a4b181a3.png)
![www2018html](https://user-images.githubusercontent.com/36680622/46954747-a90f7d00-d091-11e8-9e79-3763ddf74e82.png)

Nous n'arrivons pas à déterminer l'origine de cette différence de comportement, est-ce que vous auriez une idée?

**Comment by zufrieden** [comment]
Oui, le site http://epfl.alwaysdata.net/accueil/shortcodes/  contient une ancienne version du thème avant que nous implémentions exerpt https://github.com/epfl-idevelop/wp-theme-2018/commit/87c2038aecbc82b09d698a21a0b51bb9f22a86ac
