### ISSUE TITLE
Textbox de recherche pas affiché entre LD et XL

### ISSUE THREAD

**Issue by obieler** [epfl-idevelop/elements#323]
Le menu hamburger est caché à partir d'un screen XL (>= 1200px).
Mais le textbox de recherche est caché à partir d'un screen LD (>= 992 px).

Il faudrait qu'il soit caché qu'à partir d'un XL.

![selection_240](https://user-images.githubusercontent.com/24526380/46998823-ff2d0080-d123-11e8-8ac4-1083c63210d0.jpg)

**Solution**
Je crois qu'il faudrait mettre la classe "d-xl-none":
https://github.com/epfl-idevelop/elements/blob/e75bf635222480735998e89875cdd6650843c854/assets/components/molecules/search/search-mobile.twig#L1

Je vous laisse voir, si jamais je serai en vacances entre le 17 et 26 octobre, voir avec @williambelle si jamais.

**Comment by zufrieden** [comment]
Yep clairement un bug, merci.
