### ISSUE TITLE
[0.1] Logo EPFL mal aligné dans le header light en mobile

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/elements#329]
Le problème est visible dans la documentation pour le header light.

**Comment by zufrieden** [comment]
![screenshot 2018-11-30 at 14 52 51](https://user-images.githubusercontent.com/451236/49293206-a46f1e80-f4af-11e8-969d-5524d32aefe4.png)
- [ ] le logo EPFL devrait être aligné à gauche

**Comment by knuch** [comment]
mr-auto pour rectifier
