### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by jdelasoie** [epfl-idevelop/elements#331]
Le style des liens vers le changement de langue lorsqu'il y a deux choix ne correspond plus aux attentes : 
Voir :
https://epfl-idevelop.github.io/elements/#/atoms/nav-lang

Style attendu :
![language-switch-2](https://user-images.githubusercontent.com/15261020/47566380-dc70c800-d92b-11e8-8627-f8e7164fea75.png)

**Comment by frizzymagma** [comment]
@zufrieden Effectivement, concernant les choix de langues, ce qui est affiché dans le styleguide ne correspond pas à ce qui avait été validé.

**Comment by jdelasoie** [comment]
J'ai pu identifier que cette PR a généré le problème :
https://github.com/epfl-idevelop/elements/pull/299

**Comment by zufrieden** [comment]
- [ ] pas mettre le globe partout
- [ ] revenir au design initial des 2 langues (gras, rouge)

**Comment by zufrieden** [comment]
@jdelasoie merci de merger le PR #350 pour fixer cette issue ;-)

@frizzymagma corrigé de notre coté.
