### ISSUE TITLE
[0.5] List-group -> padding-right 0 sur écran XS à MD 

### ISSUE THREAD

**Issue by obieler** [epfl-idevelop/elements#332]
**Concerne:** 
molecules -> [list-group](https://epfl-idevelop.github.io/elements/#/molecules/list-group)

**Problème:**
En dessous de 992px, un padding-right de 0 est ajouté sur les classes _list-group_ et _list-group-teaser-content_.

Il faudrait à mon avis supprimer [cette ligne](https://github.com/epfl-idevelop/elements/blob/138f028af8d1d603ed28764d3d699073884ef54b/assets/components/molecules/list-group/list-group.scss#L58).

**Démo:**
![screenshot from 2018-10-29 16-14-20](https://user-images.githubusercontent.com/24526380/47660213-de8a8f00-db96-11e8-8834-de9941584556.png)

**Comment by zufrieden** [comment]
Attention à ne pas casser un composant qui hérite de celui-là.
C'est @Yago qui a écrit cette ligne, peut être a-t-il une idée/un souvernir de sa raison ?

Sans doute lié au "browse" à checker donc.
