### ISSUE TITLE
Typo nav-lang aria-label

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/elements#334]
https://github.com/epfl-idevelop/elements/blob/f883aade6debca4b24e2e2e9538585e66b2b3ad5/assets/components/atoms/nav-lang/nav-lang-short.twig#L4

**Comment by jdelasoie** [comment]
Is this linked with this issue ? https://github.com/epfl-idevelop/elements/issues/331

**Comment by williambelle** [comment]
Non, il y a juste un apostrophe dans le label

**Comment by jdelasoie** [comment]
Ok, corrigé
