### ISSUE TITLE
Medias

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#34]
[invision](https://projects.invisionapp.com/share/N4FDSKWX8ZB#/screens/279352923_Media)

**validated variants:**

- [x] cover image

- [x] image

- [x] video

**Comment by knuch** [comment]
@Yago You have already made some of this, this issue is for visibility purposes and be sure we don't miss anything

**Comment by Yago** [comment]
![cover](https://user-images.githubusercontent.com/2025924/40221671-640b7c5c-5a7d-11e8-9ec4-ccec8a0e31ab.png)


<img width="568" alt="capture d ecran 2018-05-18 a 09 24 02" src="https://user-images.githubusercontent.com/2025924/40221656-54cad314-5a7d-11e8-8adb-085c666edbcf.png">
