### ISSUE TITLE
[1] Problème d'affichage sur les listes (atom > lists)

### ISSUE THREAD

**Issue by obieler** [epfl-idevelop/elements#341]
-- https://epfl-idevelop.github.io/elements/#/atoms/list

1. Les bullets débordent de la marge gauche (marge négative). Elles devraient être alignées horizontalement au niveau du titre "EN RELATION" (voir exemple ci-dessous).

2. La mise à la ligne, exemple "Mediacom", devrait être aligné horizontalement au début de la première ligne ("Toutes").

3. Moins important, à mon avis l'espace entre les 2 éléments (li) devrait être plus important que l'espace entre 2 lignes d'un même élément.

![selection_220](https://user-images.githubusercontent.com/24526380/48121606-aad5f600-e275-11e8-8bc1-835c3e5b81d4.jpg)

**Comment by knuch** [comment]
l'alignement des bullets ne dehors de la colonne est un choix de design. l'alignement lors de passage sur deux lignes est un bug

**Comment by knuch** [comment]
Alignement revisité pour els bullet list et numbered list. publié dans la 1.3.8 :)
