### ISSUE TITLE
Favicons: configuration minimale ?

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/elements#344]
Je trouve l'exemple un peu exagéré bien que juste. Est-ce qu'on peut avoir un exemple d'une version minimale dans la doc ?

(https://epfl-idevelop.github.io/elements/#/atoms/favicon)

**Comment by knuch** [comment]
L'exemple est exhaustif pour tous des devices qui en ont besoin. C'est la version que nous considérons comme minimale au jour d'aujourd'hui.

Libre à vous de supprimer les favicons que vous ne considérez pas comme indispensable sur une des implémentations, mais cela aura des effets de bord sur les devices concernés qui devrons interpréter une favicon optimisée pour une autre résolution
