### ISSUE TITLE
Analytics: code snippet

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/elements#353]
Depuis https://epfl-idevelop.github.io/elements/#/doc/user%20documentation--reports.md

> To be able to generate reports, paste the following snippet right after the tag on each page of your site.

Quel tag ? (Il faudrait préciser dans le texte que c'est le `<head>`)

A quoi sert la balise `<header>`  au milieu des `<script>`?

A quoi correspond le tracking ID `UA-20398423-1`?

**Comment by jdelasoie** [comment]
Hello William,

Le tag head a été escapé à l'affichage, je corrige.

Le tracking ID est un ancien que j'avais trouvé sur un site, je vais mettre celui-ci : UA-4833294-1

Je recompose le texte pour préciser ce qui va dans header et dans script.

**Comment by jdelasoie** [comment]
Fermé avec  https://github.com/epfl-idevelop/elements/pull/354
