### ISSUE TITLE
[0.1] Footer: mauvais alignement vertical du footer-legal et copyright

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/elements#358]
Le footer-legal et le copyright ne sont pas aligné verticalement dans le footer.

![footer](https://user-images.githubusercontent.com/2843501/49138191-d7b67f80-f2ee-11e8-864a-77db82bd22e9.png)

Voir https://epfl-idevelop.github.io/elements/#/organisms/footer

**Comment by jdelasoie** [comment]
@frizzymagma N'est-ce pas voulu ? un représente les actions, l'autre une notice

**Comment by frizzymagma** [comment]
@jdelasoie @williambelle Oui, c'est voulu, pas besoin d'aligner.

**Comment by williambelle** [comment]
Quelle partie dans le code indique que c'est voulu ?

**Comment by frizzymagma** [comment]
@williambelle Je ne comprends pas.
