### ISSUE TITLE
Icônes manquantes

### ISSUE THREAD

**Issue by jaepetto** [epfl-idevelop/elements#384]
Salut,

en suivant la procédure décrite [ici](https://epfl-idevelop.github.io/elements/#/doc/user%20documentation--index.md) pour inclure le thème dans un application Django, j'obtiens une erreur 404 sur le fichiers d'icônes:
Request Method: | GET | http://localhost:8000/icons/icons.svg

Le code pour obtenir l'erreur est le suivant:
```
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Elements CSS -->
        <link rel="stylesheet" href="{% static 'epfl/elements/css/vendors.min.css' %}">
        <link rel="stylesheet" href="{% static 'epfl/elements/css/base.css' %}">

        <!-- Any custom CSS for the dashboard -->
		<link rel="stylesheet" href="{% static 'dashboard/css/styles.css' %}">
	</head>
    <body>
        {% block body_content%}{% endblock %}

        <!-- jQuery through CDN is not already present -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <!-- Elements JS -->
        <script src="{% static 'epfl/elements/js/vendors.min.js' %}"></script>
        <script src="{% static 'epfl/elements/js/vendors.bundle.js' %}"></script>
        <script src="{% static 'epfl/elements/js/app.bundle.js' %}"></script>

        <!-- Any custom script for the dasboard -->
        <script src="{% static 'dashboard/js/script.js' %}"></script>
    </body>
</html>
```

De plus, dans le cas d'applications django, il n'y a aucune garantie que les fichiers statiques ne trouvent sous `//icons/` . Ils auraient plutôt tendance à se trouver sous `/static/.../icons/`

Comment puis-je contourner le problème?

Merci d'avance,

Manu

**Comment by williambelle** [comment]
Hello,

Il y a aucune info dans la doc malheureusement mais tu peux surcharger le chemin vers les icones après l'appel à jQuery.

Par exemple, dans Actu :

```
<script>
  svgPath = 'https://web2018.epfl.ch/2.1.0/icons/icons.svg';
</script>
```

**Comment by jaepetto** [comment]
Salut @williambelle ,

merci pour l'info. C'est bien plus propre que la solution que j'avais trouvé (modifier le routage dans `urls.py`):
```
path('icons/icons.svg', RedirectView.as_view(url="/static/epfl/elements/icons/icons.svg")),
```
