### ISSUE TITLE
Broken header light in v2.0.5

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/elements#389]
Since v2.0.5, the header light is broken.

Visible in the doc: https://epfl-idevelop.github.io/elements/#/organisms/header

![broken](https://user-images.githubusercontent.com/2843501/58474819-8a578580-814c-11e9-961b-b4d5f1b072e5.png)

**Comment by jdelasoie** [comment]
Should be corrected https://github.com/epfl-idevelop/elements/pull/392

**Comment by GregLeBarbar** [comment]
Version v2.0.6 fixed the problem
