### ISSUE TITLE
[3] Header standard - adjustment --> languages

### ISSUE THREAD

**Issue by Yago** [epfl-idevelop/elements#42]
<img width="1439" alt="header-1" src="https://user-images.githubusercontent.com/2025924/39617327-9051d260-4f7f-11e8-8b14-8bc86ffea874.png">

![header-2](https://user-images.githubusercontent.com/2025924/39617330-932dde20-4f7f-11e8-9df2-16ac9a25a53e.png)

**Comment by zufrieden** [comment]
- [ ] Search behavior -> Clicking lens open display a search field with a button ?
- [ ] behavior when up to 7 languages and without any ;-)

**Comment by zufrieden** [comment]
- [ ] search input trigger https://search.epfl.ch/web.action?request_locale=en&q=toto&domain=epfl

**Comment by knuch** [comment]
Renamed this issue to follow only the language switcher topic.

Created https://github.com/epfl-idevelop/elements/issues/285 to follow the improvements relating to the search button

**Comment by knuch** [comment]
@pierre-georges / @guillaumeberry We'll need to pass on this together when you come back

**Comment by pierre-georges** [comment]
3 languages and more :
https://invis.io/9DMZV08HJ6Z#/274002806_Header-Standard
Mobile at the bottom.
On mobile, I think the best is to use the native iOS dropdown when we touch the "FR" ? @zufrieden
