### ISSUE TITLE
Header light

### ISSUE THREAD

**Issue by Yago** [epfl-idevelop/elements#43]
![header-light](https://user-images.githubusercontent.com/2025924/39617346-a92b1d32-4f7f-11e8-9512-e08274d80f3e.png)

**Comment by frizzymagma** [comment]
Pourrait-on anonymiser le logo sur l'exemple ? Merci

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 12 26](https://user-images.githubusercontent.com/130704/40055958-144790a0-584a-11e8-8bd2-3bf3abeb3d44.png)
![screen shot 2018-05-15 at 14 12 36](https://user-images.githubusercontent.com/130704/40055959-15b3c242-584a-11e8-9da8-16e973f9b71c.png)

**Comment by guillaumeberry** [comment]
Mockup was updated!
—› https://invis.io/N4FDSKWX8ZB#/279352924_Header-Light-Ultra-Light

Requirement
- [ ] Default header light logo = EPFL logo + title of the app (ex. : Actualités)
