### ISSUE TITLE
Media - Gallery / Slider

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#45]

**Comment by Yago** [comment]
![gallery](https://user-images.githubusercontent.com/2025924/39618421-ea3344ea-4f83-11e8-8e89-75eeb446820c.png)

**Comment by rdewolff** [comment]
![projects invisionapp com_share_n4fdskwx8zb 1](https://user-images.githubusercontent.com/130704/40060082-0a3a4b3c-5856-11e8-8d72-b6e1fd08252a.png)
