### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by Yago** [epfl-idevelop/elements#48]
![alerts](https://user-images.githubusercontent.com/2025924/39619063-b4861a9a-4f86-11e8-995a-103613fb7abb.png)

**Comment by Yago** [comment]
WP = Theme shortcode

**Comment by rdewolff** [comment]
![projects invisionapp com_share_n4fdskwx8zb 2](https://user-images.githubusercontent.com/130704/40060186-57998032-5856-11e8-9ce2-cc4ddef08bac.png)

Mise à jour avec contre proposition!

**Comment by Yago** [comment]
done in 05bef81f033e5456e62e4cb2b1137c16c0acb9c0
