### ISSUE TITLE
[2h] Form Filters

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#49]

**Comment by Yago** [comment]
![filters](https://user-images.githubusercontent.com/2025924/39620104-520bb59c-4f8a-11e8-86f5-d38d17ce3a4b.png)

**Comment by zufrieden** [comment]
Related to #122 ?

**Comment by tonifisler** [comment]
https://projects.invisionapp.com/d/main#/console/12550024/279353744/preview
