### ISSUE TITLE
News - basic teaser

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#51]

**Comment by Yago** [comment]
![capture d ecran 2018-05-04 a 11 12 29](https://user-images.githubusercontent.com/2025924/39620624-123a37f2-4f8c-11e8-90cf-fed168652339.png)

**Comment by knuch** [comment]
Hello @frizzymagma, il n'y avait pas d'issue correspondante, donc j'en ai créé une : https://github.com/epfl-idevelop/elements/issues/91
