### ISSUE TITLE
Event teaser - Revamp and finish

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#54]
flickity

- [x] basic

- [x] highlight

- [x] just finished 

- [x] invitation

**Comment by Yago** [comment]
![event-just-finished](https://user-images.githubusercontent.com/2025924/39622066-31596f9a-4f91-11e8-8d42-3c2e59453ad8.png)

**Comment by frizzymagma** [comment]
Event teaser : Basic 
1. Selon le design validé, les éléments devraient pouvoir être "scrollé" de gauche à droite. (Note : en version responsive, le comportement des éléments ne joue pas car ceux-ci deviennent illisibles.)
2. Affichage de la date (ou DES dates, car il y a des événements qui se déroulent sur plusieurs jours) et des horaires : 
JJ.MM.YYYY - HH:MM > HH:MM
3. S'assurer que les liens sont bien cliquables s'ils sont renseignés par l'utilisateur, notamment "lieu" et "Organisé par".

Merci

![capture d ecran 2018-05-11 a 16 35 41](https://user-images.githubusercontent.com/33958302/39930569-5e412570-553b-11e8-9f49-e2797f6099fb.png)


![capture d ecran 2018-05-11 a 16 44 32](https://user-images.githubusercontent.com/33958302/39930297-a1eac3b8-553a-11e8-9ce3-d5ee3edb8bd5.png)

**Comment by frizzymagma** [comment]
Event teaser : Highlighted + listing 
1. Informations trop collées dans le highlighted teaser, les espaces manquent entre les paragraphes 
2. Bas de composants coupés lorsqu'on passe le curseur sur les éléments du listing (comme si les composants se chevauchaient)
3. Sur le composant "listing", pour uniformiser le tout, pourrait-on avoir le même format de date que pour les autres composants (basic, highlighted, listing, etc.) ? A savoir : DD.MM.YYYY - HH:MM>HH:MM 

Merci.

![capture d ecran 2018-05-11 a 16 52 36](https://user-images.githubusercontent.com/33958302/39930927-4747047e-553c-11e8-911e-866737d02849.png)

**Comment by Yago** [comment]
@frizzymagma concernant le point **3 de l'Event teaser Basic** : 

Comme dans le design les **lieux** et **utilisateurs** ne seront pas des liens. En termes d'expérience utilisateur, nous préférons nous focaliser sur **un objectif pour un composant**, en l'occurrence les teasers vont introduire et rediriger vers une page de détail. De cette page de détails nous pourrons accéder à l'auteur, lieu et autres catégories, mais depuis le teaser, nous accéderons uniquement au détail afin de garder une constance dans les patterns de navigation et ainsi, que l'utilisateur puisse rapidement saisir la fonction du composant.
