### ISSUE TITLE
Teaser basic page - basic teaser

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#55]

**Comment by Yago** [comment]
![teaser-basic-page-basic-teaser](https://user-images.githubusercontent.com/2025924/39622325-08cde99c-4f92-11e8-9a66-d008965cbb49.png)

**Comment by rdewolff** [comment]
![projects invisionapp com_share_n4fdskwx8zb 3](https://user-images.githubusercontent.com/130704/40060615-5334a9ee-5857-11e8-9e32-516b7f407d8b.png)

**Comment by Yago** [comment]
@tonifisler only one per component as discussed
