### ISSUE TITLE
Study plan

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#56]

**Comment by zufrieden** [comment]
Ex : 
http://edu.epfl.ch/studyplan/fr/propedeutique/architecture ou 
http://edu.epfl.ch/studyplan/fr/mineur/informatique

Attention, prendre l'HTML actuel et décider ce qui est possible de styler par rapport au design proposé.

**Comment by zufrieden** [comment]
![screenshot 2018-07-24 09 18 30](https://user-images.githubusercontent.com/451236/43122824-9f4a61e6-8f22-11e8-90be-04c67b28704d.png)

**Comment by zufrieden** [comment]
SEE https://github.com/epfl-idevelop/elements/pull/171
