### ISSUE TITLE
Coursebook - Program & Reference week

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#58]

**Comment by zufrieden** [comment]
https://epfl-idevelop.github.io/elements/#/content-types/coursebook

**Comment by pierre-georges** [comment]
Existant:
https://invis.io/9DMZV08HJ6Z#/296856897_Coursebook_-_Reference_Week

**Comment by zufrieden** [comment]
Même principe que pour le studyplan on garde la même structure HTML. Du coup à réaliser en peering @Yago @pierre-georges

**Comment by knuch** [comment]
@frizzymagma @lvenries 

**coursebook (Reference week)** 
J'aurais besoin d'un exemple de markup  avec des cellules remplies, pour pouvoir le styler. De plus, j'aurais besoin de savoir jusqu'à quel point les cellules peuvent s'étendre, pour assurer de couvrir tous les situations.

**coursebook (Program)**
Est-ce que le html de ce composant peut être changé? Si on doit adapter notre javascript + css au markup actuel, cela risque de demander pas mal d'efforts et de poser des problèmes. Le plus propre serait de vous proposer un nouveau html qui restera assez proche de celui existant, mais qui suivra la même logique que le reste du styleguide.

**Comment by lvenries** [comment]
Voici la page avec les différents liens HTML https://is-academia.epfl.ch/planfiche-html
Aucun moyen de faire changer l'HTML dans un délais résonable (moins d'une année), donc il faut faire avec.

**Comment by knuch** [comment]
Hello @lvenries ! merci pour le lien. En fouillant j'ai finalement trouvé des pages où le composant reference week avait des entrées. ça me suffira pour avancer.

okay pour l'html du Program, on va faire au mieux avec ce markup

**Comment by knuch** [comment]
@lvenries Après avoir plongé dans le code, il va quand même me falloir un petit quelque chose:
Une classe `coursebook-reference-week` et une classe `coursebook-programm` sur un `div` qui entoure chacun des éléments. ça peut être un `div` existant ou un supplémentaire, cela m'est égal.

Je fais cette demande car avec les classes et le html actuels, je n'ai aucun moyen d'identifier ces éléments et de les cibler avec des règles CSS.

Est-ce que tu penses que ce serait jouable? On peut s'appeller lundi si nécessaire pour discuter du sujet :)

**Comment by lvenries** [comment]
Je ne suis pas sûr de tout bien comprende.
On vient de faire le point avec Magaly, et il y a un élèment qui n'a sans pas été très clair.
Nous avons besoin dans Wordpress du plan d'étude (programme). Voici un exemple : https://enac.epfl.ch/enseignement/architecture/bachelor/plan-etude-1ere-annee avec source https://isa.epfl.ch/pe/plan_etude_bama_prop_ar_fr.html
Pour le reference week, nous avons besoin de l'avoir dans le style guide mais il ne sera pas intérgré dans Worpdress mais directement sur la plateforme isa. Exemple : http://isa.epfl.ch/imoniteur_ISAP/!itffichecours.htm?ww_i_matiere=837374708&ww_x_anneeAcad=2018-2019&ww_i_section=942293&ww_i_niveau=6683117&ww_c_langue=fr
Pour le programme cela va être très dur de modifier le html. Que te manque-t-il et ou dans la page https://isa.epfl.ch/pe/plan_etude_bama_prop_ar_fr.html ?

**Comment by knuch** [comment]
@lvenries J'ai l'impression que tu mélanges deux concepts: 

*Study Plan* = Plan d'études 
ça c'est ce que tu m'a envoyé en lien, et qui ne concerne pas l'issue présente. Je déplace cette discussion dans une issue dédiée: https://github.com/epfl-idevelop/elements/issues/291

*Coursebook Program / reference week* 
voici les éléments dont on parle: 
<img width="346" alt="capture d ecran 2018-09-07 a 15 47 31" src="https://user-images.githubusercontent.com/4548432/45222672-6e0d7300-b2b5-11e8-9be0-ac332bf7f5df.png">
|--> Program: je suis en train de coder ce composant. J'ai gardé *exactement votre `html`* mais il me faudrait une classe pour l'identifier (voir screenshot tout en bas)

<img width="343" alt="capture d ecran 2018-09-07 a 15 47 37" src="https://user-images.githubusercontent.com/4548432/45222676-71a0fa00-b2b5-11e8-96f8-7142da50d681.png">
|--> Reference week: Pareil, je vais la coder la semaine prochaine, j'aurais besoin d'une classe pour l'identifier

Voici un schéma qui devrait parler au développeur de chez ISA qui s'occupe de l'implémentation:
(désolé pour les couleurs, j'ai fait au plus vite 😄  )
<img width="1228" alt="capture d ecran 2018-09-07 a 15 51 59" src="https://user-images.githubusercontent.com/4548432/45223047-71552e80-b2b6-11e8-82ba-9a81d5e4b24c.png">

**Comment by knuch** [comment]
@lvenries  dans la même logique, une classe `.coursebook-legend` autour de la légende sera nécessaire si on veut la styler correctement.
On peut se zoom à ce sujet si tu préfères (je suis dispo toute la journée)

**Comment by lvenries** [comment]
merci c'est en effet plus clair pour moi.
Malheureusement la personne qui s'occupe de ça côté EPFL est vancaces encore cette semaine.
Je te propose que tu définisses toi même les classes que nous implémenterons de notre côté dès que nous intégrerons ces composants. Il faut juste nous donner les noms que tu as choisi. OK pour toi ?

**Comment by knuch** [comment]
@lvenries ça marche pour moit! C'est codé (en code review) en utilisant les classes suivantes:

```
<div class="coursebook-program"></div>
<div class="coursebook-reference-week"></div>
<div class="coursebook-legend"></div>
```
