### ISSUE TITLE
Text - toggle

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#59]

**Comment by Yago** [comment]
![text-toggle](https://user-images.githubusercontent.com/2025924/39622801-c1251014-4f93-11e8-814c-10c7ce31c8a9.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 11 55 49](https://user-images.githubusercontent.com/130704/40050154-f0301a74-5836-11e8-9da7-4421f337e0da.png)
