### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Yago** [epfl-idevelop/elements#6]
[InVision](https://invis.io/N4FDSKWX8ZB#/279353744_Form-Standard-Calendar-And-Filters)

- [x] Standard
- [x] Calendar

**Comment by knuch** [comment]
@Yago After discussion with Guillaume, he designed the hover/focus of radio buttons. 

Seems that on some screens the white dot is not centered, and we could make the focus a bit more intense. 

![](https://files.slack.com/files-pri/T04D665PJ-F9N7M536Y/hop.png)
