### ISSUE TITLE
Newsletter - Sign up

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#60]

**Comment by Yago** [comment]
![capture d ecran 2018-05-04 a 12 07 24](https://user-images.githubusercontent.com/2025924/39622810-ca1fca92-4f93-11e8-8b5a-f623ff6de7c6.png)

**Comment by rdewolff** [comment]
![projects invisionapp com_share_n4fdskwx8zb 4](https://user-images.githubusercontent.com/130704/40060733-91084104-5857-11e8-9d39-47a7c300986b.png)
