### ISSUE TITLE
New wording for the cookie consent overlay

### ISSUE THREAD

**Issue by domq** [epfl-idevelop/elements#636]
(Warning: this issue may contain French words.)

Dans le cadre de l’audit sur la protection des données et la cybersécurité du CEPF, l’auditeur a noté le constat suivant et émis la recommandation [... que voici] : [...] adapter le libellé de la bannière des cookies en utilisant uniquement un texte informatif sans consentement implicite. 
 
Version FR :
 
 « Lorsque vous accédez aux sites web de l’EPFL, nous pouvons installer des cookies sur vos appareils et traiter des données personnelles vous concernant conformément à notre [politique de confidentialité](https://go.epfl.ch/protection-des-donnees). Vous pouvez bloquer les cookies à l’aide des paramètres de votre navigateur. »
 
Version EN :
 
« When you access EPFL websites, we may set cookies on your devices and process personal data about you in accordance with our [privacy policy](https://go.epfl.ch/privacy-policy). You can block cookies by using your browser settings. »

**Comment by williambelle** [comment]
Corrigé dans #637
