### ISSUE TITLE
[1h] Contact - Contact block with text

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#64]
![screenshot 2018-06-11 17 03 17](https://user-images.githubusercontent.com/451236/41239859-6d1b6814-6d99-11e8-8566-ba53c211b467.png)

**Comment by zufrieden** [comment]
Lookalike #63 
Discuss with @guillaumeberry how this is a definition list

**Comment by Yago** [comment]
Adding something like follow works just fine : 

```html
<dt>About</dt>
<dd>
  <p>Lorem ipsum ...</p>
</dd>
```
