### ISSUE TITLE
[1h] Contact - banner

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#65]
![screenshot 2018-06-06 09 51 39](https://user-images.githubusercontent.com/451236/41024340-468f8b40-696f-11e8-9142-d3b800631d3b.png)

![screenshot 2018-06-06 09 51 43](https://user-images.githubusercontent.com/451236/41024343-48377c96-696f-11e8-8c1f-43124313ab1f.png)

**Comment by tonifisler** [comment]
Is this a dynamic map?
