### ISSUE TITLE
Teaser mission - Institute

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#68]

**Comment by Yago** [comment]
![teaser-mission-institutes](https://user-images.githubusercontent.com/2025924/39624477-b68f1e1e-4f99-11e8-9e6e-3a3b7d671c90.png)

**Comment by rdewolff** [comment]
Il a été demandé d'ajouter le nom de la / les faculté/s à laquelle l'institut se rattache. Est-ce que ce commentaire a été pris en compte @guillaumeberry ?
