### ISSUE TITLE
Teaser mission - Laboratory

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#69]

**Comment by Yago** [comment]
![teaser-mission-laboratory](https://user-images.githubusercontent.com/2025924/39624470-b0a5025c-4f99-11e8-90a3-c73137cc643c.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 32 58](https://user-images.githubusercontent.com/130704/40056874-f1ab22a2-584c-11e8-91e3-33822d0ccd19.png)
![Uploading Screen Shot 2018-05-15 at 14.33.09.png…]()
