### ISSUE TITLE
Teaser mission - Research Project

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#70]

**Comment by Yago** [comment]
![teaser-mission-teaser-mission-research-project](https://user-images.githubusercontent.com/2025924/39624457-a7a27b3a-4f99-11e8-9538-bc2f3d2d03fe.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 37 29](https://user-images.githubusercontent.com/130704/40057057-85a7947c-584d-11e8-9d35-a1fe852b7105.png)
