### ISSUE TITLE
Teaser mission - Research Field

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#71]

**Comment by Yago** [comment]
![teaser-mission-teaser-mission-research-field](https://user-images.githubusercontent.com/2025924/39624404-70864f32-4f99-11e8-917b-838cd8c90c9d.png)

![teaser-mission-teaser-mission-research-field-noimg](https://user-images.githubusercontent.com/2025924/39624410-76328b9e-4f99-11e8-9ed8-65e0a98cd145.png)
