### ISSUE TITLE
Teaser mission -  Training

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#72]

**Comment by Yago** [comment]
![teaser-mission-training](https://user-images.githubusercontent.com/2025924/39624396-6b430204-4f99-11e8-89de-6d953fe28ad4.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 39 18](https://user-images.githubusercontent.com/130704/40057160-c95d45fe-584d-11e8-81a7-a1fab9863337.png)
![screen shot 2018-05-15 at 14 39 26](https://user-images.githubusercontent.com/130704/40057161-c97dfeca-584d-11e8-818c-b687a99c2ebe.png)
