### ISSUE TITLE
Teaser mission - Cursus

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#73]

**Comment by Yago** [comment]
![teaser-mission-program](https://user-images.githubusercontent.com/2025924/39624375-622c23ee-4f99-11e8-9335-1b1509a6981a.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 40 49](https://user-images.githubusercontent.com/130704/40057235-fb07d8d0-584d-11e8-9abf-9accb01eb1ba.png)
