### ISSUE TITLE
Teaser mission - Association

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#74]

**Comment by Yago** [comment]
![teaser-mission-associations](https://user-images.githubusercontent.com/2025924/39624367-5a8b6a50-4f99-11e8-9eaf-8637e34b73f2.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 44 29](https://user-images.githubusercontent.com/130704/40057401-81ea4572-584e-11e8-9cbb-68666dc099af.png)
