### ISSUE TITLE
Teaser mission - Program

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#76]

**Comment by Yago** [comment]
![teaser-mission-program](https://user-images.githubusercontent.com/2025924/39624359-54b390a8-4f99-11e8-85e0-563fa99fefd6.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 45 30](https://user-images.githubusercontent.com/130704/40057466-ac5f4370-584e-11e8-97d4-fde3d407cec2.png)
