### ISSUE TITLE
Teaser mission - Teaser bachelor

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#77]

**Comment by Yago** [comment]
![teaser-mission-bachelor](https://user-images.githubusercontent.com/2025924/39624352-4e8875fe-4f99-11e8-96bb-07a58c515ed9.png)

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 14 49 10](https://user-images.githubusercontent.com/130704/40057653-2ea373e2-584f-11e8-8ace-7f182c1a0329.png)
