### ISSUE TITLE
Restauration - Menu

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#80]
depends on https://github.com/epfl-idevelop/elements/issues/103

**Comment by rdewolff** [comment]
![screen shot 2018-05-15 at 11 55 49](https://user-images.githubusercontent.com/130704/40050577-257550a4-5838-11e8-90ed-e36a1692cf30.png)
![screen shot 2018-05-15 at 12 04 16](https://user-images.githubusercontent.com/130704/40050579-27780900-5838-11e8-9fc9-2830645e04c8.png)
![screen shot 2018-05-15 at 12 04 23](https://user-images.githubusercontent.com/130704/40050586-28de2dc4-5838-11e8-9a47-71c00ec02a6e.png)
![screen shot 2018-05-15 at 12 04 27](https://user-images.githubusercontent.com/130704/40050587-2a3fa4a4-5838-11e8-9f5d-95de7cc148ea.png)
