### ISSUE TITLE
Improve link CSS complexity

### ISSUE THREAD

**Issue by tonifisler** [epfl-idevelop/elements#84]
Today's WTF moment:

```scss
a:not([class*="btn"]):not([class*="teaser"]):not([class*="card"]):not(.social-icon):not([aria-describedby*="footnote"]):not([aria-describedby*="sidenote"]):not(.no-text-link):not(.news) {
  [...(way too much stuff)]
}
```

Strongly against that kind of specificity. How can we find a solution to fix this? Can the links that need to be styled that way have a class? Can they be inside a wrapper? This absolutely needs to be refactored.

**Comment by knuch** [comment]
Agreed. Already discussed and need to be refactored. 
I would vote for three levels of declaration:

1. a `.pretty-link` class to apply this style on links generated programatically
2. a specific selector for all wysiwyg-inputted links  (for example: `.post-content > p > a`, depending on wordpress final markup)
3. a `.unstyled` class to disable the pretty link behavior on special occasions where changing the selector is not worth it
