### ISSUE TITLE
News - Highlighted teaser

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/elements#91]
![capture d ecran 2018-05-14 a 15 57 26](https://user-images.githubusercontent.com/4548432/40002006-bbdf336a-578f-11e8-9643-be891553539b.png)

**Comment by zufrieden** [comment]
Small adjustment on this component : 
- [ ] Decrease width of ```fullwidth-teaser-content```

**Comment by zufrieden** [comment]
- [ ] Explore a way to limit highlight news image height to something around 60vh to make sure we can see a part of the 2 following news]

![screenshot 2018-07-24 14 56 47](https://user-images.githubusercontent.com/451236/43139406-f3b43d18-8f51-11e8-8480-50e706424d10.png)

- [ ] Cropping the image height for instance
